# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmnMlchXLeL9eIuNX9RVl3O2y8unTOFy
"""

# -*- coding: utf-8 -*-
"""new_소재별_추이차트 파이썬

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fDBlxJv4OI6i56UyZTqmgwp3KLCx19n-
"""

# -*- coding: utf-8 -*-
# v3-ad 통합 코드: Meta Ads API (광고별, 최근 7일만) + Mixpanel API → 스프레드시트
# ★ 최적화 핵심:
#   - Meta/Mixpanel: 최근 7일만 수집 (API 호출 대폭 절감)
#   - 기존 날짜 탭: 절대 삭제하지 않음 (과거 데이터 보존)
#   - 기존 날짜 탭 데이터를 읽어서 분석탭 생성에 활용
#   - 최근 7일 날짜 탭만 덮어쓰기/새로 생성
#   - 분석 탭만 삭제 후 재생성
#   - 날짜탭 이름: YY/MM/DD 형식
# ★ 탭 순서: [기타탭] → [날짜탭: 과거→최신] → [분석탭: 추이차트/마스터 등]
# ★ FIX: 믹스패널 매칭 0건이어도 지출 있으면 순이익(마이너스)/ROAS(0)/CVR(0) 표시
# ★ GitHub Actions 호환: 서비스 계정 인증 + GitHub Secrets

print("="*60)
print("🚀 v3-ad 통합 자동화 (최적화): 최근 7일만 수집 + 기존 탭 보존")
print("="*60)

# =========================================================
# 인증 (GitHub Actions / Colab 자동 분기)
# =========================================================
import os
import json

if 'GCP_SERVICE_ACCOUNT_KEY' in os.environ:
    # ── GitHub Actions 환경 ──
    import gspread
    from google.oauth2.service_account import Credentials

    service_account_info = json.loads(os.environ['GCP_SERVICE_ACCOUNT_KEY'])
    scopes = [
        'https://www.googleapis.com/auth/spreadsheets',
        'https://www.googleapis.com/auth/drive'
    ]
    creds = Credentials.from_service_account_info(service_account_info, scopes=scopes)
    gc = gspread.authorize(creds)
    print("✅ GitHub Actions 서비스 계정 인증 완료")
else:
    # ── Google Colab 환경 (폴백) ──
    from google.colab import auth
    auth.authenticate_user()
    import gspread
    from google.auth import default
    creds, _ = default(scopes=[
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive"
    ])
    gc = gspread.authorize(creds)
    print("✅ Google Colab 인증 완료")

# ★ 수정: 하드코딩 → 환경변수 (GitHub Secrets)
SPREADSHEET_URL = os.environ.get("SPREADSHEET_URL", "https://docs.google.com/spreadsheets/d/10bDQsuXYGHCNOpZkaZrtLYskwjIwBR-Rxv2D9fQF7fQ/edit?usp=sharing")
sh = gc.open_by_url(SPREADSHEET_URL)
print(f"✅ 스프레드시트: {sh.title}\n")

import requests as req_lib
import pandas as pd
from datetime import datetime, timedelta, timezone
import time
import random
import math
import re
import calendar
from collections import defaultdict
from gspread.exceptions import APIError

# =========================================================
# Meta Ads API 설정 — ★ 수정: 환경변수에서 토큰 로드
# =========================================================
META_TOKEN_DEFAULT = os.environ.get("META_TOKEN_1", "")

META_TOKENS = {
    "act_707835224206178":  os.environ.get("META_TOKEN_1", ""),
    "act_1270614404675034": os.environ.get("META_TOKEN_1", ""),
    "act_1808141386564262": os.environ.get("META_TOKEN_2", ""),
}

def get_token(acc_id):
    return META_TOKENS.get(acc_id, META_TOKEN_DEFAULT)
META_API_VERSION = "v21.0"
META_BASE_URL = f"https://graph.facebook.com/{META_API_VERSION}"

# =========================================================
# Mixpanel 설정 — ★ 수정: 환경변수에서 인증정보 로드
# =========================================================
MIXPANEL_PROJECT_ID = os.environ.get("MIXPANEL_PROJECT_ID", "3390233")
MIXPANEL_USERNAME = os.environ.get("MIXPANEL_USERNAME", "")
MIXPANEL_SECRET = os.environ.get("MIXPANEL_SECRET", "")
MIXPANEL_EVENT_NAME = "결제완료"

# =========================================================
# 기본 설정
# =========================================================
KST = timezone(timedelta(hours=9))
TODAY = datetime.now(KST).replace(tzinfo=None)
CURRENT_YEAR = TODAY.year
CURRENT_MONTH = TODAY.month
DATA_START_DATE = datetime(2026, 1, 1)

# ★★★ 핵심 변경: 최근 7일만 수집 ★★★
REFRESH_DAYS = 7
WEEKLY_TREND_REFRESH_WEEKS = 2

DATE_TAB_HEADERS = [
    "캠페인 이름", "광고 세트 이름", "광고 이름", "광고 세트 ID", "광고 ID",
    "지출 금액 (KRW)", "결과당 비용", "구매 ROAS(광고 지출 대비 수익률)",
    "CPM(1,000회 노출당 비용)", "도달", "노출",
    "고유 아웃바운드 클릭", "고유 아웃바운드 CTR(클릭률)", "고유 아웃바운드 클릭당 비용",
    "빈도", "결과",
    "결과(믹스패널)", "매출", "이익", "ROAS", "CVR",
    "기존 예산", "증액률", "변동 예산", "메모",
]

print(f"📅 현재 날짜: {TODAY.strftime('%Y-%m-%d')} (KST)")
print(f"📅 Meta/Mixpanel 수집: 최근 {REFRESH_DAYS}일만")
print(f"📅 기존 날짜 탭: 보존 (삭제 안 함)")
print(f"📅 최근 {REFRESH_DAYS}일 탭만 덮어쓰기/새로 생성")
print()

PRODUCT_KEYWORDS = ["재물", "솔로", "재회", "29금궁합", "자녀", "29금", "1%", "별해"]
WEEKDAY_NAMES = ['월', '화', '수', '목', '금', '토', '일']

COLORS = {
    "dark_gray": {"red":0.4,"green":0.4,"blue":0.4}, "black": {"red":0.2,"green":0.2,"blue":0.2},
    "light_gray": {"red":0.9,"green":0.9,"blue":0.9}, "light_gray2": {"red":0.95,"green":0.95,"blue":0.95},
    "white": {"red":1,"green":1,"blue":1}, "green": {"red":0.56,"green":0.77,"blue":0.49},
    "light_yellow": {"red":1.0,"green":0.98,"blue":0.8}, "light_blue": {"red":0.85,"green":0.92,"blue":0.98},
    "light_red": {"red":1.0,"green":0.85,"blue":0.85}, "dark_blue": {"red":0.2,"green":0.3,"blue":0.5},
    "navy": {"red":0.15,"green":0.2,"blue":0.35}, "dark_green": {"red":0.2,"green":0.5,"blue":0.3},
    "orange": {"red":0.9,"green":0.5,"blue":0.2}, "purple": {"red":0.5,"green":0.3,"blue":0.6},
}

SUMMARY_PRODUCTS = ["집착", "결혼", "커리어", "1%", "별해", "솔로", "재물", "재회", "29금궁합", "자녀", "29금"]
ANALYSIS_TAB_NAMES = ["추이차트", "추이차트(주간)", "증감액", "예산", "주간종합", "주간종합_2", "주간종합_3", "마스터탭", "소재랭킹"]

# =========================================================
# 유틸리티 함수 (원본과 동일)
# =========================================================
def with_retry(fn, *args, max_retries=8, **kwargs):
    for attempt in range(max_retries):
        try:
            return fn(*args, **kwargs)
        except APIError as e:
            if "429" in str(e) or "Quota exceeded" in str(e):
                wait_time = 20 + (attempt * 15) + random.random()
                print(f"  ⏳ Sheets Rate limit. {wait_time:.0f}초 대기 (시도 {attempt+1}/{max_retries})")
                time.sleep(wait_time)
            elif attempt == max_retries-1:
                raise
            else:
                time.sleep(5 + random.random())
    return None

def clean_id(val):
    if val is None: return ""
    s = str(val).strip()
    if not s: return ""
    try:
        if ("E" in s or "e" in s) and re.match(r'^[\d.]+[eE][+\-]?\d+$', s):
            return str(int(float(s)))
    except: pass
    try:
        if re.match(r'^\d+\.\d+$', s):
            return str(int(float(s)))
    except: pass
    if re.match(r'^\d+$', s): return s
    numeric_only = re.sub(r'[^0-9]', '', s)
    return numeric_only if numeric_only else s

def extract_product(cn):
    for p in PRODUCT_KEYWORDS:
        if p in cn: return p
    return "기타"

def normalize_date_key(ds):
    try:
        parts = ds.split('/')
        if len(parts) == 3:
            return f"{int(parts[0]):02d}/{int(parts[1]):02d}/{int(parts[2]):02d}"
        elif len(parts) == 2:
            m, d = int(parts[0]), int(parts[1])
            year = 2026 if m <= 3 else 2025
            return f"{year % 100:02d}/{m:02d}/{d:02d}"
        return ds
    except: return ds

def _to_num(x):
    try:
        v = str(x).replace(",","").replace("₩","").replace("%","").replace("\\","").replace("W","").replace("￦","").strip()
        return float(v) if v and v not in ["-","#DIV/0!"] else 0.0
    except: return 0.0

def money(n):
    try: return f"₩{int(round(float(n))):,}"
    except: return "₩0"

def cell_text(profit, revenue, spend, cpm=0, cvr=0):
    if spend == 0: return ""
    roas = (revenue / spend * 100) if spend > 0 else 0
    return f"{roas:.0f}\n{money(profit)}\n-{money(spend)}\n{'₩'+str(int(round(cpm)))+'' if cpm > 0 else '₩0'}\n{cvr:.1f}%"

def cell_text_change(roas, chg, spend, cpm, cvr=0):
    if spend == 0: return ""
    cl = f"+{chg:.1f}%" if chg > 0 else f"{chg:.1f}%" if chg < 0 else "0.0%"
    return f"{roas:.0f}\n{cl}\n-{money(spend)}\n{'₩'+str(int(round(cpm))) if cpm > 0 else '₩0'}\n{cvr:.1f}%"

def find_col(headers, kws):
    for kw in kws:
        kl = kw.lower()
        for i, h in enumerate(headers):
            if kl in str(h).lower(): return i
    return None

def get_week_range(d):
    wd = d.weekday(); m = d - timedelta(days=wd); s = m + timedelta(days=6)
    return f"'{m.month}/{m.day}({WEEKDAY_NAMES[0]})~{s.month}/{s.day}({WEEKDAY_NAMES[6]})"

def get_week_range_short(d):
    wd = d.weekday(); m = d - timedelta(days=wd); s = m + timedelta(days=6)
    return f"{m.month}/{m.day}~{s.month}/{s.day}"

def get_month_range_display(f, l):
    return f"'{f.month}.{f.day}~{l.month}.{l.day}"

def get_week_monday(d):
    return d - timedelta(days=d.weekday())

def parse_date_tab(tab_name):
    if '/' not in tab_name: return None
    if tab_name in ANALYSIS_TAB_NAMES: return None
    try:
        parts = tab_name.split('/')
        if len(parts) == 3:
            y, m, d = int(parts[0]), int(parts[1]), int(parts[2])
            year = 2000 + y
            return datetime(year, m, d)
        elif len(parts) == 2:
            m, d = int(parts[0]), int(parts[1])
            year = 2026 if m <= 3 else 2025
            return datetime(year, m, d)
        return None
    except: return None

def get_cell_format(bg=None, tc=None, bold=False, ha="CENTER"):
    f = {"horizontalAlignment": ha, "verticalAlignment": "MIDDLE"}
    if bg: f["backgroundColor"] = bg
    if tc or bold:
        f["textFormat"] = {}
        if tc: f["textFormat"]["foregroundColor"] = tc
        if bold: f["textFormat"]["bold"] = True
    return f

def create_format_request(sid, sr, er, sc, ec, fmt):
    return {"repeatCell": {"range": {"sheetId": sid, "startRowIndex": sr, "endRowIndex": er, "startColumnIndex": sc, "endColumnIndex": ec}, "cell": {"userEnteredFormat": fmt}, "fields": "userEnteredFormat"}}

def create_border_request(sid, sr, er, sc, ec):
    bs = {"style": "SOLID", "width": 1, "color": {"red": 0.7, "green": 0.7, "blue": 0.7}}
    return {"updateBorders": {"range": {"sheetId": sid, "startRowIndex": sr, "endRowIndex": er, "startColumnIndex": sc, "endColumnIndex": ec}, "top": bs, "bottom": bs, "left": bs, "right": bs, "innerHorizontal": bs, "innerVertical": bs}}

def create_number_format_request(sid, sr, er, sc, ec, ft="NUMBER", p="#,##0"):
    return {"repeatCell": {"range": {"sheetId": sid, "startRowIndex": sr, "endRowIndex": er, "startColumnIndex": sc, "endColumnIndex": ec}, "cell": {"userEnteredFormat": {"numberFormat": {"type": ft, "pattern": p}}}, "fields": "userEnteredFormat.numberFormat"}}

def apply_c2_label_formatting(sh, ws):
    sid = ws.id; cv = "ROAS\n순이익\n지출금액\nCPM\nCVR"
    lines = cv.split('\n'); indices = [0]; pos = 0
    for line in lines[:-1]: pos += len(line) + 1; indices.append(pos)
    bk = {"foregroundColor": {"red":0,"green":0,"blue":0}}
    dg = {"foregroundColor": {"red":0.22,"green":0.46,"blue":0.11}}
    rd = {"foregroundColor": {"red":0.85,"green":0.0,"blue":0.0}}
    bl = {"foregroundColor": {"red":0.0,"green":0.0,"blue":0.85}}
    req = {"updateCells": {"range": {"sheetId": sid, "startRowIndex": 1, "endRowIndex": 2, "startColumnIndex": 2, "endColumnIndex": 3},
        "rows": [{"values": [{"userEnteredValue": {"stringValue": cv}, "textFormatRuns": [
            {"startIndex": indices[0], "format": bk}, {"startIndex": indices[1], "format": dg},
            {"startIndex": indices[2], "format": rd}, {"startIndex": indices[3], "format": bl},
            {"startIndex": indices[4], "format": bk}]}]}], "fields": "userEnteredValue,textFormatRuns"}}
    with_retry(sh.batch_update, body={"requests": [req]}); time.sleep(1)

def apply_trend_chart_formatting(sh, ws, headers, rows_count, is_change_tab=False, sunday_col_indices=None, format_col_end=None):
    sid = ws.id
    try: with_retry(ws.format, 'A1:Z1', {'backgroundColor': {'red':0.9,'green':0.9,'blue':0.9}, 'textFormat': {'bold': True}}); time.sleep(1)
    except: pass
    if sunday_col_indices:
        try:
            sr = [create_format_request(sid, 0, 1, ci, ci+1, get_cell_format(COLORS["light_red"], bold=True)) for ci in sunday_col_indices]
            if sr: with_retry(sh.batch_update, body={"requests": sr}); time.sleep(1)
        except: pass
    try: with_retry(ws.format, 'A2:Z2', {'textFormat': {'bold': True}}); time.sleep(1)
    except: pass
    try: with_retry(sh.batch_update, body={"requests": [{"updateSheetProperties": {"properties": {"sheetId": sid, "gridProperties": {"frozenRowCount": 1}}, "fields": "gridProperties.frozenRowCount"}}]}); time.sleep(2)
    except: pass
    try: with_retry(ws.format, 'D2:Z1000', {'wrapStrategy': 'WRAP', 'verticalAlignment': 'TOP'}); time.sleep(1)
    except: pass
    try:
        cwr = [{"updateDimensionProperties": {"range": {"sheetId": sid, "dimension": "COLUMNS", "startIndex": cn, "endIndex": cn+1}, "properties": {"pixelSize": 95}, "fields": "pixelSize"}} for cn in range(3, min(len(headers), 26))]
        if cwr: with_retry(sh.batch_update, body={"requests": cwr})
    except: pass

    print("  🎨 ROAS 조건부 서식...")
    try:
        sc, ec = 3, len(headers)
        rules = [
            {'c': '=AND(NOT(ISBLANK(INDIRECT(ADDRESS(ROW(),COLUMN())))),LEN(TRIM(INDIRECT(ADDRESS(ROW(),COLUMN()))))>0,VALUE(LEFT(INDIRECT(ADDRESS(ROW(),COLUMN())),FIND(CHAR(10),INDIRECT(ADDRESS(ROW(),COLUMN()))&CHAR(10))-1))=0)', 'clr': {'red':1.0,'green':0.6,'blue':0.6}},
            {'c': '=AND(NOT(ISBLANK(INDIRECT(ADDRESS(ROW(),COLUMN())))),LEN(TRIM(INDIRECT(ADDRESS(ROW(),COLUMN()))))>0,VALUE(LEFT(INDIRECT(ADDRESS(ROW(),COLUMN())),FIND(CHAR(10),INDIRECT(ADDRESS(ROW(),COLUMN()))&CHAR(10))-1))>=300)', 'clr': {'red':0.6,'green':1.0,'blue':1.0}},
            {'c': '=AND(NOT(ISBLANK(INDIRECT(ADDRESS(ROW(),COLUMN())))),LEN(TRIM(INDIRECT(ADDRESS(ROW(),COLUMN()))))>0,VALUE(LEFT(INDIRECT(ADDRESS(ROW(),COLUMN())),FIND(CHAR(10),INDIRECT(ADDRESS(ROW(),COLUMN()))&CHAR(10))-1))>=200,VALUE(LEFT(INDIRECT(ADDRESS(ROW(),COLUMN())),FIND(CHAR(10),INDIRECT(ADDRESS(ROW(),COLUMN()))&CHAR(10))-1))<300)', 'clr': {'red':0.7,'green':1.0,'blue':0.7}},
            {'c': '=AND(NOT(ISBLANK(INDIRECT(ADDRESS(ROW(),COLUMN())))),LEN(TRIM(INDIRECT(ADDRESS(ROW(),COLUMN()))))>0,VALUE(LEFT(INDIRECT(ADDRESS(ROW(),COLUMN())),FIND(CHAR(10),INDIRECT(ADDRESS(ROW(),COLUMN()))&CHAR(10))-1))>=100,VALUE(LEFT(INDIRECT(ADDRESS(ROW(),COLUMN())),FIND(CHAR(10),INDIRECT(ADDRESS(ROW(),COLUMN()))&CHAR(10))-1))<200)', 'clr': {'red':1.0,'green':1.0,'blue':0.6}},
            {'c': '=AND(NOT(ISBLANK(INDIRECT(ADDRESS(ROW(),COLUMN())))),LEN(TRIM(INDIRECT(ADDRESS(ROW(),COLUMN()))))>0,VALUE(LEFT(INDIRECT(ADDRESS(ROW(),COLUMN())),FIND(CHAR(10),INDIRECT(ADDRESS(ROW(),COLUMN()))&CHAR(10))-1))<100,VALUE(LEFT(INDIRECT(ADDRESS(ROW(),COLUMN())),FIND(CHAR(10),INDIRECT(ADDRESS(ROW(),COLUMN()))&CHAR(10))-1))>0)', 'clr': {'red':1.0,'green':0.8,'blue':0.8}},
        ]
        fr = [{'addConditionalFormatRule': {'rule': {'ranges': [{'sheetId': sid, 'startRowIndex': 1, 'endRowIndex': rows_count+2, 'startColumnIndex': sc, 'endColumnIndex': ec}],
            'booleanRule': {'condition': {'type': 'CUSTOM_FORMULA', 'values': [{'userEnteredValue': r['c']}]}, 'format': {'backgroundColor': r['clr']}}}, 'index': 0}} for r in rules]
        with_retry(sh.batch_update, body={'requests': fr}); time.sleep(3)
    except Exception as e:
        print(f"  ⚠️ 조건부 서식 오류: {e}")

    tcs = 3
    tce = min(format_col_end or len(headers), len(headers), 20)
    print(f"  🎨 텍스트 색상 (col {tcs}~{tce-1})...")
    try:
        fr = []
        bk = {"foregroundColor":{"red":0,"green":0,"blue":0}}
        dg3 = {"foregroundColor":{"red":0.22,"green":0.46,"blue":0.11}}
        rd = {"foregroundColor":{"red":0.85,"green":0.0,"blue":0.0}}
        gn = {"foregroundColor":{"red":0.0,"green":0.7,"blue":0.0}}
        bl = {"foregroundColor":{"red":0.0,"green":0.0,"blue":0.85}}
        for ci in range(tcs, tce):
            try: cv = with_retry(ws.col_values, ci+1)
            except: continue
            if not cv or len(cv) < 2: continue
            for ri in range(2, min(len(cv)+1, rows_count+3)):
                val = cv[ri-1] if ri-1 < len(cv) else ""
                if not val or '\n' not in val: continue
                lines = val.split('\n')
                if len(lines) < 4: continue
                l1e = len(lines[0]); l2e = l1e+1+len(lines[1]); l3e = l2e+1+len(lines[2]); l4s = l3e+1
                if len(lines) >= 5: l4e = l4s+len(lines[3]); l5s = l4e+1
                if is_change_tab:
                    cc = gn if lines[1].startswith('+') else rd if lines[1].startswith('-') else bk
                    tr = [{"startIndex":0,"format":bk},{"startIndex":l1e+1,"format":cc},{"startIndex":l2e+1,"format":rd},{"startIndex":l4s,"format":bl}]
                else:
                    tr = [{"startIndex":0,"format":bk},{"startIndex":l1e+1,"format":dg3},{"startIndex":l2e+1,"format":rd},{"startIndex":l4s,"format":bl}]
                if len(lines) >= 5: tr.append({"startIndex":l5s,"format":bk})
                fr.append({"updateCells":{"range":{"sheetId":sid,"startRowIndex":ri-1,"endRowIndex":ri,"startColumnIndex":ci,"endColumnIndex":ci+1},"rows":[{"values":[{"userEnteredValue":{"stringValue":val},"textFormatRuns":tr}]}],"fields":"userEnteredValue,textFormatRuns"}})
                if len(fr) >= 300:
                    try: with_retry(sh.batch_update, body={"requests": fr}); fr = []; time.sleep(3)
                    except: fr = []
        if fr:
            try: with_retry(sh.batch_update, body={"requests": fr}); time.sleep(2)
            except: pass
        print("  ✅ 텍스트 색상 완료")
    except Exception as e:
        print(f"  ⚠️ 텍스트 색상 오류: {e}")


# =========================================================
# Meta Ads API 함수 (원본과 동일)
# =========================================================
def meta_api_get(url, params=None, token=None):
    if params is None: params = {}
    params['access_token'] = token or META_TOKEN_DEFAULT
    for attempt in range(5):
        try:
            resp = req_lib.get(url, params=params, timeout=120)
            if resp.status_code == 200: return resp.json()
            elif resp.status_code == 400:
                err = resp.json().get('error', {})
                print(f"  ❌ Meta 400: {err.get('message', resp.text[:200])}")
                return None
            elif resp.status_code in [429, 500, 502, 503]:
                wait = 30 + attempt * 30
                print(f"  ⏳ Meta {resp.status_code}, {wait}초 대기 (시도 {attempt+1}/5)")
                time.sleep(wait)
            else:
                print(f"  ❌ Meta {resp.status_code}: {resp.text[:200]}")
                if attempt < 4: time.sleep(15)
                else: return None
        except Exception as e:
            print(f"  ❌ Meta 요청 오류: {e}")
            if attempt < 4: time.sleep(15)
            else: return None
    return None


def extract_action_value(al, types):
    if not al: return 0
    for a in al:
        if a.get('action_type','') in types:
            try: return float(a.get('value',0))
            except: return 0
    return 0


def fetch_meta_insights_daily(ad_account_id, single_date, active_ids=None):
    url = f"{META_BASE_URL}/{ad_account_id}/insights"
    fields = 'campaign_name,adset_name,adset_id,ad_name,ad_id,spend,cpm,reach,impressions,frequency,actions,cost_per_action_type,purchase_roas,unique_outbound_clicks,unique_outbound_clicks_ctr,cost_per_unique_outbound_click'

    params = {
        'fields': fields,
        'level': 'ad',
        'time_increment': 1,
        'time_range': json.dumps({'since': single_date, 'until': single_date}),
        'limit': 500,
        'filtering': json.dumps([{'field': 'spend', 'operator': 'GREATER_THAN', 'value': '0'}])
    }

    all_results = []
    data = meta_api_get(url, params, token=get_token(ad_account_id))
    while data:
        rows = data.get('data', [])
        all_results.extend(rows)
        paging = data.get('paging', {})
        next_url = paging.get('next')
        if next_url:
            time.sleep(1)
            try:
                resp = req_lib.get(next_url, timeout=120)
                data = resp.json() if resp.status_code == 200 else None
            except: data = None
        else:
            break

    if active_ids:
        all_results = [r for r in all_results if r.get('ad_id') in active_ids]

    return all_results


def parse_single_day_insights(rows, date_str, date_obj):
    purchase_types = ['purchase', 'omni_purchase', 'offsite_conversion.fb_pixel_purchase']
    outbound_types = ['outbound_click']
    parsed = []

    for row in rows:
        spend = float(row.get('spend', 0))
        cpm = float(row.get('cpm', 0))
        reach = int(float(row.get('reach', 0)))
        impressions = int(float(row.get('impressions', 0)))
        frequency = float(row.get('frequency', 0))

        actions = row.get('actions', [])
        results = extract_action_value(actions, purchase_types)
        cost_per_action = row.get('cost_per_action_type', [])
        cost_per_result = extract_action_value(cost_per_action, purchase_types)
        purchase_roas_list = row.get('purchase_roas', [])
        meta_roas = extract_action_value(purchase_roas_list, purchase_types)

        uo = row.get('unique_outbound_clicks', [])
        unique_clicks = extract_action_value(uo, outbound_types)
        uc = row.get('unique_outbound_clicks_ctr', [])
        unique_ctr = extract_action_value(uc, outbound_types)
        cpu = row.get('cost_per_unique_outbound_click', [])
        cost_per_click = extract_action_value(cpu, outbound_types)

        parsed.append({
            'campaign_name': row.get('campaign_name', ''),
            'adset_name': row.get('adset_name', ''),
            'ad_name': row.get('ad_name', ''),
            'adset_id': row.get('adset_id', ''),
            'ad_id': row.get('ad_id', ''),
            'spend': spend, 'cost_per_result': cost_per_result,
            'meta_roas': meta_roas, 'cpm': cpm, 'reach': reach,
            'impressions': impressions, 'unique_clicks': unique_clicks,
            'unique_ctr': unique_ctr, 'cost_per_unique_click': cost_per_click,
            'frequency': frequency, 'results': results,
            'date_obj': date_obj,
        })
    return parsed


# =========================================================
# Mixpanel 함수 (원본과 동일)
# =========================================================
def fetch_mixpanel_data(from_date, to_date):
    url = "https://data.mixpanel.com/api/2.0/export"
    params = {'from_date': from_date, 'to_date': to_date,
              'event': json.dumps([MIXPANEL_EVENT_NAME]), 'project_id': MIXPANEL_PROJECT_ID}
    print(f"  📡 Mixpanel: {from_date} ~ {to_date}")
    try:
        resp = req_lib.get(url, params=params, auth=(MIXPANEL_USERNAME, MIXPANEL_SECRET), timeout=300)
        if resp.status_code != 200:
            print(f"  ❌ Mixpanel {resp.status_code}"); return []
        lines = [l for l in resp.text.split('\n') if l.strip()]
        print(f"  📊 이벤트: {len(lines)}건")
        data = []
        stat_amount_only = 0
        stat_value_only = 0
        stat_both = 0
        stat_neither = 0

        for line in lines:
            try:
                ev = json.loads(line); props = ev.get('properties', {})
                ts = props.get('time', 0)
                if ts:
                    dt_kst = datetime.fromtimestamp(ts, tz=timezone.utc) + timedelta(hours=9)
                    ds = f"{dt_kst.year % 100:02d}/{dt_kst.month:02d}/{dt_kst.day:02d}"
                else: ds = None
                ut = None
                for k in ['utm_content','UTM_Content','UTM Content']:
                    if k in props and props[k]: ut = str(props[k]).strip(); break
                if ut:
                    ut = clean_id(ut)

                raw_amount = props.get('amount')
                raw_value = props.get('value')

                amount_val = 0.0
                if raw_amount is not None:
                    try: amount_val = float(raw_amount)
                    except: amount_val = 0.0

                value_val = 0.0
                if raw_value is not None:
                    try: value_val = float(raw_value)
                    except: value_val = 0.0

                if amount_val > 0:
                    revenue = amount_val
                elif value_val > 0:
                    revenue = value_val
                else:
                    revenue = 0.0

                has_amount = amount_val > 0
                has_value = value_val > 0
                if has_amount and has_value: stat_both += 1
                elif has_amount: stat_amount_only += 1
                elif has_value: stat_value_only += 1
                else: stat_neither += 1

                data.append({
                    'distinct_id': props.get('distinct_id'),
                    'time': ts, 'date': ds,
                    'utm_content': ut or '',
                    'amount': amount_val,
                    'value_raw': value_val,
                    'revenue': revenue,
                    '서비스': props.get('서비스', ''),
                })
            except: pass

        print(f"  ✅ 파싱: {len(data)}건")
        print(f"  📊 매출 출처 분석:")
        print(f"    - amount만 있음: {stat_amount_only}건")
        print(f"    - value만 있음: {stat_value_only}건")
        print(f"    - 둘 다 있음 (amount 사용): {stat_both}건")
        print(f"    - 둘 다 없음 (매출 0): {stat_neither}건")
        return data
    except Exception as e:
        print(f"  ❌ Mixpanel 오류: {e}"); return []


# =========================================================
# 날짜탭 하단 요약표 관련 함수 (원본과 동일)
# =========================================================
def match_summary_product(campaign_name, product_keyword):
    cn = campaign_name
    if product_keyword == "29금":
        return "29금" in cn and "29금궁합" not in cn
    else:
        return product_keyword in cn


def generate_date_tab_summary(rows):
    total_spend = 0.0
    total_meta_purchase = 0.0
    total_mp_purchase = 0.0
    total_revenue = 0.0
    total_profit = 0.0
    total_unique_clicks = 0.0
    spend_by_account = {"본계정": 0.0, "부계정": 0.0, "3rd계정": 0.0}

    prod_spend = {p: 0.0 for p in SUMMARY_PRODUCTS}
    prod_revenue = {p: 0.0 for p in SUMMARY_PRODUCTS}
    prod_profit = {p: 0.0 for p in SUMMARY_PRODUCTS}

    for row in rows:
        cn = str(row[0]) if len(row) > 0 else ""
        adset_id = str(row[3]) if len(row) > 3 else ""
        spend = _to_num(row[5]) if len(row) > 5 else 0
        meta_p = _to_num(row[15]) if len(row) > 15 else 0
        mp_p = _to_num(row[16]) if len(row) > 16 else 0
        rev = _to_num(row[17]) if len(row) > 17 else 0
        prof = _to_num(row[18]) if len(row) > 18 else 0
        uc = _to_num(row[11]) if len(row) > 11 else 0

        if not cn or cn in ["전체", "합계", "Total"]:
            continue

        total_spend += spend
        total_meta_purchase += meta_p
        total_mp_purchase += mp_p
        total_revenue += rev
        total_profit += prof
        total_unique_clicks += uc

        if adset_id.startswith("12023"):
            spend_by_account["본계정"] += spend
        elif adset_id.startswith("12024"):
            spend_by_account["부계정"] += spend
        elif adset_id.startswith("6"):
            spend_by_account["3rd계정"] += spend

        for p in SUMMARY_PRODUCTS:
            if match_summary_product(cn, p):
                prod_spend[p] += spend
                prod_revenue[p] += rev
                prod_profit[p] += prof
                break

    total_roas = (total_revenue / total_spend * 100) if total_spend > 0 else 0
    total_cvr = (total_mp_purchase / total_unique_clicks * 100) if total_unique_clicks > 0 else 0

    summary_data = []
    summary_data.append([""] * 25)
    summary_data.append([""] * 25)

    r_title = [""] * 25
    r_title[14] = "전체"
    summary_data.append(r_title)

    r_hdr = [""] * 25
    r_hdr[11] = "본계정"; r_hdr[12] = "부계정"; r_hdr[13] = "3rd 계정"
    r_hdr[14] = "지출 금액 (KRW)"; r_hdr[15] = "구매 (메타)"; r_hdr[16] = "구매 (믹스패널)"
    r_hdr[17] = "매출"; r_hdr[18] = "이익"; r_hdr[19] = "ROAS"; r_hdr[20] = "CVR"
    summary_data.append(r_hdr)

    r_val = [""] * 25
    r_val[11] = round(spend_by_account["본계정"])
    r_val[12] = round(spend_by_account["부계정"])
    r_val[13] = round(spend_by_account["3rd계정"])
    r_val[14] = round(total_spend)
    r_val[15] = round(total_meta_purchase)
    r_val[16] = round(total_mp_purchase)
    r_val[17] = round(total_revenue)
    r_val[18] = round(total_profit)
    r_val[19] = round(total_roas, 1)
    r_val[20] = total_cvr / 100 if total_cvr else 0
    summary_data.append(r_val)

    sp = SUMMARY_PRODUCTS
    total_prod_spend = sum(prod_spend[p] for p in sp)
    total_prod_revenue = sum(prod_revenue[p] for p in sp)
    total_prod_profit = sum(prod_profit[p] for p in sp)

    tables = [
        ("제품별 ROAS", "roas"),
        ("제품별 순이익", "profit"),
        ("제품별 매출", "revenue"),
        ("제품별 순이익율", "profit_margin"),
        ("제품별 예산", "spend"),
        ("제품별 예산 비중", "spend_ratio"),
    ]

    for table_title, data_type in tables:
        summary_data.append([""] * 25)
        r_tt = [""] * 25
        r_tt[12] = table_title
        summary_data.append(r_tt)

        r_ph = [""] * 25
        for i, p in enumerate(sp):
            r_ph[9 + i] = p
        r_ph[9 + len(sp)] = "합"
        summary_data.append(r_ph)

        r_pv = [""] * 25
        for i, p in enumerate(sp):
            ps = prod_spend[p]; pr = prod_revenue[p]; pp = prod_profit[p]
            if data_type == "roas": r_pv[9 + i] = pr / ps if ps > 0 else 0
            elif data_type == "profit": r_pv[9 + i] = round(pp)
            elif data_type == "revenue": r_pv[9 + i] = round(pr)
            elif data_type == "profit_margin": r_pv[9 + i] = pp / pr if pr > 0 else 0
            elif data_type == "spend": r_pv[9 + i] = round(ps)
            elif data_type == "spend_ratio": r_pv[9 + i] = ps / total_prod_spend if total_prod_spend > 0 else 0

        if data_type == "roas": r_pv[20] = total_prod_revenue / total_prod_spend if total_prod_spend > 0 else 0
        elif data_type == "profit": r_pv[20] = round(total_prod_profit)
        elif data_type == "revenue": r_pv[20] = round(total_prod_revenue)
        elif data_type == "profit_margin": r_pv[20] = total_prod_profit / total_prod_revenue if total_prod_revenue > 0 else 0
        elif data_type == "spend": r_pv[20] = round(total_prod_spend)
        elif data_type == "spend_ratio": r_pv[20] = ""

        summary_data.append(r_pv)

    return summary_data


def format_date_tab_summary(sh, ws, data_row_count, summary_row_count):
    sid = ws.id
    base = data_row_count + 1

    C_PINK = {"red":0.957,"green":0.8,"blue":0.8}
    C_ORANGE = {"red":0.988,"green":0.898,"blue":0.804}
    C_LGREEN = {"red":0.851,"green":0.918,"blue":0.827}
    C_GRAY = {"red":0.69,"green":0.7,"blue":0.698}
    C_DGRAY = {"red":0.6,"green":0.6,"blue":0.6}
    C_BLACK = {"red":0,"green":0,"blue":0}
    C_WHITE = {"red":1,"green":1,"blue":1}
    C_LYELLOW = {"red":1,"green":1,"blue":0.8}

    fmt_requests = []

    r = base + 2
    fmt_requests.append(create_format_request(sid, r, r+1, 14, 21, {
        "horizontalAlignment": "CENTER", "textFormat": {"bold": True}
    }))
    fmt_requests.append({"mergeCells": {"range": {"sheetId": sid, "startRowIndex": r, "endRowIndex": r+1, "startColumnIndex": 14, "endColumnIndex": 21}, "mergeType": "MERGE_ALL"}})

    r = base + 3
    hdr_fmt_base = {"textFormat": {"bold": True, "foregroundColor": C_BLACK}, "horizontalAlignment": "CENTER", "verticalAlignment": "MIDDLE"}
    fmt_requests.append(create_format_request(sid, r, r+1, 13, 14, {**hdr_fmt_base, "backgroundColor": C_PINK}))
    fmt_requests.append(create_format_request(sid, r, r+1, 12, 13, {**hdr_fmt_base, "backgroundColor": C_ORANGE}))
    fmt_requests.append(create_format_request(sid, r, r+1, 13, 14, {**hdr_fmt_base, "backgroundColor": C_LGREEN}))
    fmt_requests.append(create_format_request(sid, r, r+1, 14, 20, {**hdr_fmt_base, "backgroundColor": C_GRAY}))
    fmt_requests.append(create_format_request(sid, r, r+1, 20, 21, {**hdr_fmt_base, "backgroundColor": C_DGRAY}))

    r = base + 4
    fmt_requests.append(create_number_format_request(sid, r, r+1, 11, 20, "NUMBER", "#,##0"))
    fmt_requests.append(create_number_format_request(sid, r, r+1, 19, 20, "NUMBER", "#,##0.0"))
    fmt_requests.append(create_number_format_request(sid, r, r+1, 20, 21, "NUMBER", "0.00%"))
    fmt_requests.append(create_border_request(sid, base+3, base+5, 11, 21))

    table_formats = [
        ("ROAS",      "0.00%"),
        ("순이익",    "[$₩-412]#,##0"),
        ("매출",      "#,##0"),
        ("순이익율",  "0.00%"),
        ("예산",      "[$₩-412]#,##0"),
        ("예산비중",  "0.00%"),
    ]

    offset = base + 5
    prod_hdr_fmt = {**hdr_fmt_base, "backgroundColor": C_GRAY}

    for t_idx, (tname, nfmt) in enumerate(table_formats):
        t_start = offset + t_idx * 4
        fmt_requests.append(create_format_request(sid, t_start+1, t_start+2, 14, 21, {
            "horizontalAlignment": "CENTER", "textFormat": {"bold": True}
        }))
        fmt_requests.append({"mergeCells": {"range": {"sheetId": sid, "startRowIndex": t_start+1, "endRowIndex": t_start+2, "startColumnIndex": 14, "endColumnIndex": 20}, "mergeType": "MERGE_ALL"}})
        fmt_requests.append(create_format_request(sid, t_start+2, t_start+3, 9, 21, prod_hdr_fmt))
        fmt_requests.append(create_number_format_request(sid, t_start+3, t_start+4, 9, 21, "NUMBER", nfmt))

        if t_idx in [1, 2, 4]:
            fmt_requests.append(create_format_request(sid, t_start+3, t_start+4, 20, 21, {
                "backgroundColor": C_LYELLOW, "textFormat": {"bold": True}
            }))
            fmt_requests.append(create_number_format_request(sid, t_start+3, t_start+4, 20, 21, "NUMBER", "[$₩-412]#,##0"))

        fmt_requests.append(create_border_request(sid, t_start+2, t_start+4, 9, 21))

    return fmt_requests


# =============================================================================
# ★★★ 실행 시작 — 이하 코드는 원본과 100% 동일 (변경 없음) ★★★
# =============================================================================

# =========================================================
# 1단계: 광고 계정 설정
# =========================================================
print("\n" + "="*60)
print("1단계: 광고 계정 설정")
print("="*60)

ALL_AD_ACCOUNTS = [
    "act_707835224206178",
    "act_1270614404675034",
    "act_1808141386564262",
]
print(f"📋 사용할 광고 계정 ({len(ALL_AD_ACCOUNTS)}개):")
for acc in ALL_AD_ACCOUNTS:
    print(f"  - {acc}")
print()


# =========================================================
# ★★★ 2단계: 기존 날짜 탭 읽기 (과거 데이터 로드) ★★★
# =========================================================
print("="*60)
print("2단계: 기존 날짜 탭에서 과거 데이터 읽기")
print("="*60)

ad_sets = defaultdict(lambda: {'campaign_name': '', 'adset_name': '', 'ad_name': '', 'adset_id': '', 'ad_id': '', 'dates': {}})
budget_by_date = defaultdict(lambda: defaultdict(lambda: {'spend': 0.0, 'revenue': 0.0}))
product_count = defaultdict(int)
date_objects = {}
date_tab_rows = defaultdict(list)
master_raw_data = []
master_headers = ["Date"] + DATE_TAB_HEADERS

refresh_date_keys = set()
for day_offset in range(REFRESH_DAYS):
    target_date = TODAY - timedelta(days=day_offset)
    dk = f"{target_date.year % 100:02d}/{target_date.month:02d}/{target_date.day:02d}"
    refresh_date_keys.add(dk)

print(f"  🔄 새로 수집할 날짜 ({REFRESH_DAYS}일): {sorted(refresh_date_keys)}")

existing_sheets = sh.worksheets()
existing_date_tabs = []
read_count = 0

for ws_ex in existing_sheets:
    tn = ws_ex.title
    dt_obj = parse_date_tab(tn)
    if dt_obj is None:
        continue

    existing_date_tabs.append(tn)
    dk = normalize_date_key(tn)

    if dk in refresh_date_keys:
        print(f"  ⏭️ {tn} - 새로 수집 예정, 읽기 건너뜀")
        continue

    print(f"  📖 {tn} 읽는 중...")
    try:
        all_values = with_retry(ws_ex.get_all_values)
        time.sleep(1)

        if not all_values or len(all_values) < 2:
            print(f"    ⚠️ 빈 탭")
            continue

        headers = all_values[0]
        date_objects[dk] = dt_obj

        data_rows = []
        empty_count = 0
        for row in all_values[1:]:
            if not row or not str(row[0]).strip():
                empty_count += 1
                if empty_count >= 2:
                    break
            else:
                empty_count = 0
                data_rows.append(row)

        for row in data_rows:
            cn = str(row[0]) if len(row) > 0 else ""
            asn = str(row[1]) if len(row) > 1 else ""
            adn = str(row[2]) if len(row) > 2 else ""
            asid = str(row[3]) if len(row) > 3 else ""
            adi = clean_id(row[4]) if len(row) > 4 else ""

            sp = _to_num(row[5]) if len(row) > 5 else 0
            cpr = _to_num(row[6]) if len(row) > 6 else 0
            mr = _to_num(row[7]) if len(row) > 7 else 0
            cpm = _to_num(row[8]) if len(row) > 8 else 0
            reach = _to_num(row[9]) if len(row) > 9 else 0
            imp = _to_num(row[10]) if len(row) > 10 else 0
            uc = _to_num(row[11]) if len(row) > 11 else 0
            uctr = _to_num(row[12]) if len(row) > 12 else 0
            cpuc = _to_num(row[13]) if len(row) > 13 else 0
            freq = _to_num(row[14]) if len(row) > 14 else 0
            results = _to_num(row[15]) if len(row) > 15 else 0
            mpc = _to_num(row[16]) if len(row) > 16 else 0
            mpv = _to_num(row[17]) if len(row) > 17 else 0
            pf = _to_num(row[18]) if len(row) > 18 else 0
            roas_c = _to_num(row[19]) if len(row) > 19 else 0
            cvr_c = _to_num(row[20]) if len(row) > 20 else 0

            if not cn or sp == 0:
                continue

            tab_row = list(row[:25]) if len(row) >= 25 else list(row) + [""] * (25 - len(row))
            date_tab_rows[dk].append(tab_row)

            k = adi
            if not ad_sets[k]['ad_id']:
                ad_sets[k] = {'campaign_name': cn, 'adset_name': asn, 'ad_name': adn, 'adset_id': asid, 'ad_id': adi, 'dates': {}}
            ad_sets[k]['dates'][dk] = {
                'profit': pf, 'revenue': mpv, 'spend': sp,
                'cpm': cpm, 'cvr': cvr_c, 'unique_clicks': uc
            }

            p = extract_product(cn)
            budget_by_date[dk][p]['spend'] += sp
            budget_by_date[dk][p]['revenue'] += mpv
            product_count[p] += 1

            mrd = [dk] + tab_row
            while len(mrd) < len(master_headers): mrd.append("")
            master_raw_data.append({'date': dk, 'date_obj': dt_obj, 'spend': sp, 'row_data': mrd[:len(master_headers)]})

        read_count += 1
        print(f"    ✅ {len(data_rows)}개 광고")

        if read_count % 5 == 0:
            time.sleep(3)

    except Exception as e:
        print(f"    ⚠️ 읽기 오류: {e}")
        time.sleep(2)

print(f"\n✅ 기존 날짜 탭 읽기 완료: {read_count}개 탭, {len(ad_sets)}개 광고")
print()


# =========================================================
# 3단계: Meta Ads API (★ 최근 7일만 조회)
# =========================================================
print("="*60)
print(f"3단계: Meta Insights 수집 (최근 {REFRESH_DAYS}일만)")
print("="*60)

meta_date_data = defaultdict(list)
meta_success_count = 0

for day_offset in range(REFRESH_DAYS):
    target_date = TODAY - timedelta(days=day_offset)
    target_str = target_date.strftime('%Y-%m-%d')
    date_key = f"{target_date.year % 100:02d}/{target_date.month:02d}/{target_date.day:02d}"

    print(f"\n📅 {target_str} ({date_key}) 조회 중...")

    day_rows = []
    for acc_id in ALL_AD_ACCOUNTS:
        print(f"  📡 계정 {acc_id}...")
        rows = fetch_meta_insights_daily(acc_id, target_str, active_ids=None)
        if rows:
            parsed = parse_single_day_insights(rows, date_key, target_date)
            day_rows.extend(parsed)
            print(f"  ✅ {len(parsed)}건")
        else:
            print(f"  ⚠️ 0건")
        time.sleep(2)

    if day_rows:
        meta_date_data[date_key] = day_rows
        meta_success_count += len(day_rows)
        print(f"  📊 {date_key} 합계: {len(day_rows)}개 광고")
    else:
        print(f"  ⚠️ {date_key} 데이터 없음")

print(f"\n✅ Meta 수집 완료: {len(meta_date_data)}일, 총 {meta_success_count}건")
print()


# =========================================================
# 4단계: Mixpanel 수집 (★ 최근 7일만)
# =========================================================
print("="*60)
print(f"4단계: Mixpanel 수집 (최근 {REFRESH_DAYS}일만)")
print("="*60)

mp_from = (TODAY - timedelta(days=REFRESH_DAYS-1)).strftime('%Y-%m-%d')
mp_to = TODAY.strftime('%Y-%m-%d')
mp_raw = fetch_mixpanel_data(mp_from, mp_to)

df = pd.DataFrame(mp_raw)
print(f"  원본: {len(df)}건")

mp_value_map = {}
mp_count_map = {}

if len(df) > 0:
    df = df[df['utm_content'].notna() & (df['utm_content'] != '') & (df['utm_content'] != 'None')]
    print(f"  UTM Content 있는 것: {len(df)}건")

    df = df.sort_values('revenue', ascending=False)
    bf = len(df)
    df_d = df.drop_duplicates(subset=['date', 'distinct_id', '서비스'], keep='first')
    print(f"  중복 제거: {bf} → {len(df_d)}건")

    total_revenue = df_d['revenue'].sum()
    print(f"  📊 매출 합계: ₩{int(total_revenue):,}")

    for (d, ut), v in df_d.groupby(['date', 'utm_content'])['revenue'].sum().items():
        if d and ut: mp_value_map[(d, str(ut))] = v
    for (d, ut), c in df_d.groupby(['date', 'utm_content']).size().items():
        if d and ut: mp_count_map[(d, str(ut))] = c

    print(f"  날짜+UTM Content 조합: {len(mp_value_map)}개")
print()


# =========================================================
# 5단계: Meta + Mixpanel 병합
# =========================================================
print("="*60)
print("5단계: 최근 7일 Meta + Mixpanel 병합 (기존 데이터에 추가/덮어쓰기)")
print("  ★ FIX: 믹스패널 0건이어도 순이익(마이너스)/ROAS(0)/CVR(0) 표시")
print("="*60)

new_date_names = []

for dk in sorted(meta_date_data.keys(),
    key=lambda x: meta_date_data[x][0]['date_obj'] if meta_date_data[x] else datetime.min, reverse=True):

    rows = meta_date_data[dk]
    if not rows: continue
    dt = rows[0]['date_obj']
    date_objects[dk] = dt
    new_date_names.append(dk)

    for asi in list(ad_sets.keys()):
        if dk in ad_sets[asi]['dates']:
            del ad_sets[asi]['dates'][dk]
    budget_by_date[dk] = defaultdict(lambda: {'spend': 0.0, 'revenue': 0.0})
    date_tab_rows[dk] = []

    master_raw_data = [m for m in master_raw_data if m['date'] != dk]

    for mr in rows:
        adi = mr['ad_id']; cn = mr['campaign_name']; asn = mr['adset_name']
        adn = mr['ad_name']; asid = mr['adset_id']
        sp = mr['spend']; cm = mr['cpm']; uc = mr['unique_clicks']

        mpk = (dk, adi)
        mpv = mp_value_map.get(mpk, 0)
        mpc = mp_count_map.get(mpk, 0)

        rv = mpv; pf = rv - sp
        roas_c = (rv / sp * 100) if sp > 0 else 0
        cvr_c = (mpc / uc * 100) if uc > 0 else 0

        tab_row = [
            cn, asn, adn, asid, adi, sp, mr['cost_per_result'], mr['meta_roas'],
            cm, mr['reach'], mr['impressions'], uc, mr['unique_ctr'],
            mr['cost_per_unique_click'], mr['frequency'], mr['results'],
            mpc,
            mpv,
            round(pf, 0),
            round(roas_c, 1) if sp > 0 else 0,
            round(cvr_c, 2) if uc > 0 else 0,
            "", "", "", "",
        ]
        date_tab_rows[dk].append(tab_row)

        k = adi
        if not ad_sets[k]['ad_id']:
            ad_sets[k] = {'campaign_name': cn, 'adset_name': asn, 'ad_name': adn, 'adset_id': asid, 'ad_id': adi, 'dates': {}}
        ad_sets[k]['dates'][dk] = {'profit': pf, 'revenue': rv, 'spend': sp, 'cpm': cm, 'cvr': cvr_c, 'unique_clicks': uc}

        p = extract_product(cn)
        budget_by_date[dk][p]['spend'] += sp
        budget_by_date[dk][p]['revenue'] += rv
        product_count[p] += 1

        mrd = [dk] + tab_row
        while len(mrd) < len(master_headers): mrd.append("")
        master_raw_data.append({'date': dk, 'date_obj': dt, 'spend': sp, 'row_data': mrd[:len(master_headers)]})

all_dk = list(set(date_objects.keys()))
all_dk.sort(key=lambda x: date_objects[x], reverse=False)
date_names = all_dk

new_date_names.sort(key=lambda x: date_objects[x])

print(f"✅ 전체 광고: {len(ad_sets)}개")
print(f"📅 전체 날짜 (기존+신규): {len(date_names)}개")
print(f"📅 이번에 새로 생성할 탭 (과거→최신): {new_date_names}")
print(f"📦 제품별: {dict(product_count)}")
print()


# =========================================================
# 5.5: 주간 집계
# =========================================================
print("="*60)
print("5.5: 주간 집계")
print("="*60)

week_groups = defaultdict(list)
week_display_names = {}
for t in date_names:
    do = date_objects[t]
    wk = get_week_range_short(do); wd = get_week_range(do)
    week_groups[wk].append(t); week_display_names[wk] = wd

week_ranges = []
for wr in week_groups:
    sd = week_groups[wr][0]; sdo = date_objects[sd]; m = get_week_monday(sdo)
    week_ranges.append((wr, m))
week_ranges.sort(key=lambda x: x[1], reverse=False)
week_keys = [wr[0] for wr in week_ranges]
print(f"✅ 주차: {len(week_keys)}개")

ad_sets_weekly = defaultdict(lambda: {'campaign_name':'','ad_name':'','ad_id':'','weeks':{}})
for asi, d in ad_sets.items():
    ad_sets_weekly[asi]['campaign_name'] = d['campaign_name']
    ad_sets_weekly[asi]['ad_name'] = d['ad_name']
    ad_sets_weekly[asi]['ad_id'] = d['ad_id']
    for wk in week_keys:
        wp,wr_v,ws_v = 0,0,0; wcs,wcc = 0,0; wvs,wvc = 0,0
        for dn in week_groups[wk]:
            if dn in d['dates']:
                wp += d['dates'][dn]['profit']; wr_v += d['dates'][dn]['revenue']; ws_v += d['dates'][dn]['spend']
                cv = d['dates'][dn].get('cpm',0)
                if cv > 0: wcs += cv; wcc += 1
                vv = d['dates'][dn].get('cvr',0)
                if vv > 0: wvs += vv; wvc += 1
        if ws_v > 0 or wr_v > 0:
            ad_sets_weekly[asi]['weeks'][wk] = {'profit':wp,'revenue':wr_v,'spend':ws_v,
                'cpm':(wcs/wcc) if wcc > 0 else 0,'cvr':(wvs/wvc) if wvc > 0 else 0}


# =========================================================
# 6: 정렬
# =========================================================
print("\n6: 정렬")
latest_date = date_names[-1] if date_names else ""
sorted_list = []
for asi, d in ad_sets.items():
    sp = d['dates'].get(latest_date, {}).get('spend', 0)
    sorted_list.append({'campaign_name':d['campaign_name'],'ad_name':d['ad_name'],
                        'ad_id':d['ad_id'],'data':d,'spend':sp})
sorted_list.sort(key=lambda x: x['spend'], reverse=True)

product_spend = {p: budget_by_date[latest_date][p]['spend'] for p in PRODUCT_KEYWORDS + ["기타"]}
product_order = sorted(PRODUCT_KEYWORDS + ["기타"], key=lambda p: product_spend.get(p,0), reverse=True)
if "기타" in product_order and product_spend.get("기타",0) == 0: product_order.remove("기타")
print(f"📦 제품 순서: {product_order}\n")

chart_dn = list(reversed(date_names))
chart_wk = list(reversed(week_keys))
chart_sd = chart_dn[:7]


# =========================================================
# 7: 분석 시트만 삭제 + 최근 7일 탭 삭제 (재생성 예정)
# =========================================================
print("="*60)
print("7: 분석 시트 삭제 + 최근 7일 탭만 삭제 (재생성)")
print("  ★ 기존 날짜 탭은 보존 ★")
print("="*60)

analysis_sheets = ["마스터탭", "추이차트", "증감액", "추이차트(주간)", "주간종합", "주간종합_2", "주간종합_3", "예산", "_temp", "_temp_holder"]
for sn in analysis_sheets:
    try:
        old = sh.worksheet(sn)
        if len(sh.worksheets()) <= 1:
            with_retry(sh.add_worksheet, title="_tmp", rows=1, cols=1); time.sleep(1)
        sh.del_worksheet(old)
        print(f"  ✅ '{sn}' 삭제")
        time.sleep(2)
    except gspread.exceptions.WorksheetNotFound: pass
    except Exception as e:
        print(f"  ⚠️ '{sn}' 삭제 실패: {e}"); time.sleep(3)

for dk in new_date_names:
    try:
        old = sh.worksheet(dk)
        sh.del_worksheet(old)
        print(f"  ✅ '{dk}' 삭제 (재생성 예정)")
        time.sleep(2)
    except gspread.exceptions.WorksheetNotFound: pass
    except: time.sleep(2)

print("⏳ 5초 대기...")
time.sleep(5)


# =========================================================
# 8: 최근 7일 날짜 탭만 생성
# =========================================================
print("\n" + "="*60)
print(f"8: 최근 {len(new_date_names)}개 날짜 탭만 생성 (하단 요약표 포함)")
print("="*60)

for dk in new_date_names:
    rows = date_tab_rows.get(dk, [])
    if not rows: continue

    rows.sort(key=lambda r: _to_num(r[18]) if len(r) > 18 else 0, reverse=True)

    print(f"  📅 {dk} ({len(rows)}개 광고)")

    summary_rows = generate_date_tab_summary(rows)

    try:
        total_rows = len(rows) + len(summary_rows) + 5
        NUM_COLS = len(DATE_TAB_HEADERS)
        ws_d = with_retry(sh.add_worksheet, title=dk, rows=total_rows, cols=NUM_COLS + 2)
        time.sleep(1)
        sid_d = ws_d.id
        data_end = len(rows) + 1

        all_data = [DATE_TAB_HEADERS] + rows + summary_rows
        with_retry(ws_d.update, values=all_data, range_name="A1", value_input_option="USER_ENTERED")

        fmt_all = []

        fmt_all.append(create_format_request(sid_d, 0, 1, 0, 5, {
            "textFormat": {"bold": True}, "wrapStrategy": "WRAP", "verticalAlignment": "MIDDLE"
        }))
        fmt_all.append(create_format_request(sid_d, 0, 1, 5, 16, {
            "backgroundColor": {"red":0.937,"green":0.937,"blue":0.937},
            "textFormat": {"bold": True}, "wrapStrategy": "WRAP", "verticalAlignment": "MIDDLE"
        }))
        fmt_all.append(create_format_request(sid_d, 0, 1, 16, 21, {
            "backgroundColor": {"red":0.6,"green":0.6,"blue":0.6},
            "textFormat": {"bold": True}, "wrapStrategy": "WRAP", "horizontalAlignment": "CENTER", "verticalAlignment": "MIDDLE"
        }))
        fmt_all.append(create_format_request(sid_d, 0, 1, 21, 22, {
            "backgroundColor": {"red":0.851,"green":0.824,"blue":0.914},
            "textFormat": {"bold": True}, "wrapStrategy": "WRAP", "horizontalAlignment": "CENTER", "verticalAlignment": "MIDDLE"
        }))
        fmt_all.append(create_format_request(sid_d, 0, 1, 22, 23, {
            "backgroundColor": {"red":0.706,"green":0.655,"blue":0.839},
            "textFormat": {"bold": True, "foregroundColor": {"red":1,"green":1,"blue":1}},
            "wrapStrategy": "WRAP", "horizontalAlignment": "CENTER", "verticalAlignment": "MIDDLE"
        }))
        fmt_all.append(create_format_request(sid_d, 0, 1, 23, 24, {
            "backgroundColor": {"red":0.6,"green":0,"blue":1},
            "textFormat": {"bold": True, "foregroundColor": {"red":1,"green":1,"blue":1}},
            "wrapStrategy": "WRAP", "horizontalAlignment": "CENTER", "verticalAlignment": "MIDDLE"
        }))
        fmt_all.append(create_format_request(sid_d, 0, 1, 24, 25, {
            "backgroundColor": {"red":1,"green":0.6,"blue":0},
            "textFormat": {"bold": True}, "wrapStrategy": "WRAP", "verticalAlignment": "MIDDLE"
        }))

        fmt_all.append(create_number_format_request(sid_d, 1, data_end, 16, 17, "NUMBER", "#,##0"))
        fmt_all.append(create_number_format_request(sid_d, 1, data_end, 17, 18, "NUMBER", "#,##0"))
        fmt_all.append(create_number_format_request(sid_d, 1, data_end, 18, 19, "NUMBER", "#,##0"))
        fmt_all.append(create_number_format_request(sid_d, 1, data_end, 19, 20, "NUMBER", "#,##0"))
        fmt_all.append(create_number_format_request(sid_d, 1, data_end, 20, 21, "NUMBER", "#,##0.00"))
        fmt_all.append(create_number_format_request(sid_d, 0, 1, 22, 23, "NUMBER", "0%"))
        fmt_all.append(create_number_format_request(sid_d, 1, data_end, 22, 23, "NUMBER", "0%"))
        fmt_all.append(create_number_format_request(sid_d, 1, data_end, 23, 24, "NUMBER", "0.0"))

        col_widths = [(0,210),(1,207),(2,207),(3,96),(4,96)]
        for ci, w in col_widths:
            fmt_all.append({"updateDimensionProperties": {
                "range": {"sheetId": sid_d, "dimension": "COLUMNS", "startIndex": ci, "endIndex": ci+1},
                "properties": {"pixelSize": w}, "fields": "pixelSize"
            }})

        fmt_all.append({
            "setBasicFilter": {
                "filter": {
                    "range": {"sheetId": sid_d, "startRowIndex": 0, "endRowIndex": data_end,
                              "startColumnIndex": 0, "endColumnIndex": NUM_COLS}
                }
            }
        })

        fmt_all.append({
            "updateSheetProperties": {
                "properties": {"sheetId": sid_d, "gridProperties": {"frozenRowCount": 1, "frozenColumnCount": 5}},
                "fields": "gridProperties.frozenRowCount,gridProperties.frozenColumnCount"
            }
        })

        profit_cond = [
            ("NUMBER_GREATER", "0",      {"red":1,"green":0.949,"blue":0.8},    None),
            ("NUMBER_GREATER", "50000",  {"red":1,"green":0.898,"blue":0.6},    None),
            ("NUMBER_GREATER", "100000", {"red":0.576,"green":0.769,"blue":0.49}, None),
            ("NUMBER_GREATER", "200000", {"red":0,"green":1,"blue":0},          None),
            ("NUMBER_GREATER", "300000", {"red":0,"green":1,"blue":1},          None),
            ("NUMBER_LESS", "-10000",  {"red":0.957,"green":0.8,"blue":0.8},   None),
            ("NUMBER_LESS", "-50000",  {"red":0.878,"green":0.4,"blue":0.4},   {"red":0,"green":0,"blue":0}),
        ]
        for ctype, val, bg, fc in profit_cond:
            rule_fmt = {"backgroundColor": bg}
            if fc: rule_fmt["textFormat"] = {"foregroundColor": fc}
            fmt_all.append({
                "addConditionalFormatRule": {
                    "rule": {
                        "ranges": [{"sheetId": sid_d, "startRowIndex": 1, "endRowIndex": data_end, "startColumnIndex": 18, "endColumnIndex": 19}],
                        "booleanRule": {
                            "condition": {"type": ctype, "values": [{"userEnteredValue": val}]},
                            "format": rule_fmt
                        }
                    }, "index": 0
                }
            })

        fmt_all.append({
            "addConditionalFormatRule": {
                "rule": {
                    "ranges": [{"sheetId": sid_d, "startRowIndex": 1, "endRowIndex": data_end, "startColumnIndex": 18, "endColumnIndex": 19}],
                    "gradientRule": {
                        "minpoint":  {"color": {"red":0.902,"green":0.486,"blue":0.451}, "type": "MIN"},
                        "midpoint":  {"color": {"red":1,"green":1,"blue":1}, "type": "NUMBER", "value": "0"},
                        "maxpoint":  {"color": {"red":0.341,"green":0.733,"blue":0.541}, "type": "MAX"}
                    }
                }, "index": 0
            }
        })

        roas_cond = [
            ("NUMBER_LESS",            "100", {"red":0.878,"green":0.4,"blue":0.4}),
            ("NUMBER_GREATER_THAN_EQ", "100", {"red":1,"green":0.851,"blue":0.4}),
            ("NUMBER_GREATER_THAN_EQ", "200", {"red":0.576,"green":0.769,"blue":0.49}),
            ("NUMBER_GREATER_THAN_EQ", "300", {"red":0,"green":1,"blue":1}),
        ]
        for ctype, val, bg in roas_cond:
            fmt_all.append({
                "addConditionalFormatRule": {
                    "rule": {
                        "ranges": [{"sheetId": sid_d, "startRowIndex": 1, "endRowIndex": data_end, "startColumnIndex": 19, "endColumnIndex": 20}],
                        "booleanRule": {
                            "condition": {"type": ctype, "values": [{"userEnteredValue": val}]},
                            "format": {"backgroundColor": bg}
                        }
                    }, "index": 0
                }
            })

        fmt_all.append({
            "addConditionalFormatRule": {
                "rule": {
                    "ranges": [{"sheetId": sid_d, "startRowIndex": 1, "endRowIndex": data_end, "startColumnIndex": 20, "endColumnIndex": 21}],
                    "gradientRule": {
                        "minpoint": {"color": {"red":1,"green":1,"blue":1}, "type": "MIN"},
                        "maxpoint": {"color": {"red":0.341,"green":0.733,"blue":0.541}, "type": "MAX"}
                    }
                }, "index": 0
            }
        })

        try:
            with_retry(sh.batch_update, body={"requests": fmt_all})
            time.sleep(2)
        except Exception as e:
            print(f"    ⚠️ 서식 오류: {e}")

        try:
            fmt_reqs = format_date_tab_summary(sh, ws_d, len(rows), len(summary_rows))
            if fmt_reqs:
                for i in range(0, len(fmt_reqs), 50):
                    with_retry(sh.batch_update, body={"requests": fmt_reqs[i:i+50]})
                    time.sleep(1)
        except Exception as e:
            print(f"    ⚠️ 요약표 서식 오류: {e}")

        time.sleep(1)
    except Exception as e:
        print(f"  ⚠️ {dk} 생성 오류: {e}")

print(f"\n✅ {len(new_date_names)}개 날짜 탭 생성 완료 (요약표 포함)")
time.sleep(3)


# =========================================================
# 9: 마스터탭
# =========================================================
print("\n9: 마스터탭 생성")
ws_m = with_retry(sh.add_worksheet, title="마스터탭", rows=max(2000, len(master_raw_data)+100), cols=len(master_headers)+5)
time.sleep(3)

master_raw_data.sort(key=lambda x: (x['date_obj'], -x['spend']), reverse=True)
for item in master_raw_data:
    while len(item['row_data']) < len(master_headers): item['row_data'].append("")
    item['row_data'] = item['row_data'][:len(master_headers)]

mr_all = [master_headers] + [i['row_data'] for i in master_raw_data]
for i in range(0, len(mr_all), 5000):
    with_retry(ws_m.update, values=mr_all[i:i+5000], range_name=f"A{i+1}", value_input_option="USER_ENTERED"); time.sleep(2)
try:
    with_retry(ws_m.format, 'A1:T1', {'backgroundColor':{'red':0.9,'green':0.9,'blue':0.9},'textFormat':{'bold':True}})
    with_retry(sh.batch_update, body={"requests":[{"updateSheetProperties":{"properties":{"sheetId":ws_m.id,"gridProperties":{"frozenRowCount":1}},"fields":"gridProperties.frozenRowCount"}}]})
except: pass
print("✅ 마스터탭 완료")
time.sleep(2)


# =========================================================
# 10: 추이차트 (일간)
# =========================================================
print("\n10: 추이차트 (일간)")
ws_t = with_retry(sh.add_worksheet, title="추이차트", rows=1000, cols=100); time.sleep(3)

dhw = []; sci = []
for i, n in enumerate(chart_dn):
    do = date_objects[n]; wd = WEEKDAY_NAMES[do.weekday()]
    dhw.append(f"{n}({wd})")
    if do.weekday() == 6: sci.append(4+i)

hdr_t = ['캠페인 이름','광고 이름','광고 ID','7일 평균'] + dhw

sr = ["종합","",""]
tp,tr,ts = 0,0,0; tcs,tcc = 0,0; tvs,tvc = 0,0
for d in chart_sd:
    for it in sorted_list:
        if d in it['data']['dates']:
            tp += it['data']['dates'][d]['profit']; tr += it['data']['dates'][d]['revenue']; ts += it['data']['dates'][d]['spend']
            cv = it['data']['dates'][d].get('cpm',0)
            if cv>0: tcs+=cv; tcc+=1
            vv = it['data']['dates'][d].get('cvr',0)
            if vv>0: tvs+=vv; tvc+=1
sr.append(cell_text(tp,tr,ts,(tcs/tcc) if tcc>0 else 0,(tvs/tvc) if tvc>0 else 0))

for d in chart_dn:
    dp,dr,ds_v = 0,0,0; dcs,dcc = 0,0; dvs,dvc = 0,0
    for it in sorted_list:
        if d in it['data']['dates']:
            dp += it['data']['dates'][d]['profit']; dr += it['data']['dates'][d]['revenue']; ds_v += it['data']['dates'][d]['spend']
            cv = it['data']['dates'][d].get('cpm',0)
            if cv>0: dcs+=cv; dcc+=1
            vv = it['data']['dates'][d].get('cvr',0)
            if vv>0: dvs+=vv; dvc+=1
    sr.append(cell_text(dp,dr,ds_v,(dcs/dcc) if dcc>0 else 0,(dvs/dvc) if dvc>0 else 0))

rt = []
for it in sorted_list:
    r = [it['campaign_name'],it['ad_name'],it['ad_id']]
    tp,tr,ts = 0,0,0; tcs,tcc = 0,0; tvs,tvc = 0,0
    for d in chart_sd:
        if d in it['data']['dates']:
            tp+=it['data']['dates'][d]['profit']; tr+=it['data']['dates'][d]['revenue']; ts+=it['data']['dates'][d]['spend']
            cv=it['data']['dates'][d].get('cpm',0)
            if cv>0: tcs+=cv; tcc+=1
            vv=it['data']['dates'][d].get('cvr',0)
            if vv>0: tvs+=vv; tvc+=1
    r.append(cell_text(tp,tr,ts,(tcs/tcc) if tcc>0 else 0,(tvs/tvc) if tvc>0 else 0))
    for d in chart_dn:
        if d in it['data']['dates']:
            dt=it['data']['dates'][d]
            r.append(cell_text(dt['profit'],dt['revenue'],dt['spend'],dt.get('cpm',0),dt.get('cvr',0)))
        else: r.append('')
    rt.append(r)

with_retry(ws_t.update, values=[hdr_t]+[sr]+rt, range_name="A1", value_input_option="USER_ENTERED")
print("✅ 추이차트 데이터 완료"); time.sleep(3)
apply_trend_chart_formatting(sh, ws_t, hdr_t, len(rt), sunday_col_indices=sci)
apply_c2_label_formatting(sh, ws_t)
print("⏳ 30초 대기..."); time.sleep(30)


# =========================================================
# 11: 추이차트(주간)
# =========================================================
print("\n11: 추이차트(주간)")
ws_tw = with_retry(sh.add_worksheet, title="추이차트(주간)", rows=1000, cols=100); time.sleep(3)

wdl = [week_display_names[wk] for wk in chart_wk]
hdr_w = ['캠페인 이름','광고 이름','광고 ID','전체 평균'] + wdl

srw = ["종합","",""]
tap,tar,tas = 0,0,0; tacs,tacc = 0,0; tavs,tavc = 0,0
for wk in chart_wk:
    for it in sorted_list:
        wd = ad_sets_weekly[it['ad_id']]['weeks'].get(wk,{})
        if wd:
            tap+=wd['profit']; tar+=wd['revenue']; tas+=wd['spend']
            cv=wd.get('cpm',0)
            if cv>0: tacs+=cv; tacc+=1
            vv=wd.get('cvr',0)
            if vv>0: tavs+=vv; tavc+=1
srw.append(cell_text(tap,tar,tas,(tacs/tacc) if tacc>0 else 0,(tavs/tavc) if tavc>0 else 0))
for wk in chart_wk:
    wp,wr_v,ws_v = 0,0,0; wcs,wcc = 0,0; wvs,wvc = 0,0
    for it in sorted_list:
        wd = ad_sets_weekly[it['ad_id']]['weeks'].get(wk,{})
        if wd:
            wp+=wd['profit']; wr_v+=wd['revenue']; ws_v+=wd['spend']
            cv=wd.get('cpm',0)
            if cv>0: wcs+=cv; wcc+=1
            vv=wd.get('cvr',0)
            if vv>0: wvs+=vv; wvc+=1
    srw.append(cell_text(wp,wr_v,ws_v,(wcs/wcc) if wcc>0 else 0,(wvs/wvc) if wvc>0 else 0))

rtw = []
for it in sorted_list:
    r = [it['campaign_name'],it['ad_name'],it['ad_id']]
    tp,tr,ts = 0,0,0; tcs,tcc = 0,0; tvs,tvc = 0,0
    for wk in chart_wk:
        wd = ad_sets_weekly[it['ad_id']]['weeks'].get(wk,{})
        if wd:
            tp+=wd['profit']; tr+=wd['revenue']; ts+=wd['spend']
            cv=wd.get('cpm',0)
            if cv>0: tcs+=cv; tcc+=1
            vv=wd.get('cvr',0)
            if vv>0: tvs+=vv; tvc+=1
    r.append(cell_text(tp,tr,ts,(tcs/tcc) if tcc>0 else 0,(tvs/tvc) if tvc>0 else 0))
    for wk in chart_wk:
        wd = ad_sets_weekly[it['ad_id']]['weeks'].get(wk,{})
        r.append(cell_text(wd['profit'],wd['revenue'],wd['spend'],wd.get('cpm',0),wd.get('cvr',0)) if wd else '')
    rtw.append(r)

with_retry(ws_tw.update, values=[hdr_w]+[srw]+rtw, range_name="A1", value_input_option="USER_ENTERED")
print("✅ 추이차트(주간) 완료"); time.sleep(3)
wfce = 3+1+WEEKLY_TREND_REFRESH_WEEKS
apply_trend_chart_formatting(sh, ws_tw, hdr_w, len(rtw), format_col_end=wfce)
apply_c2_label_formatting(sh, ws_tw)
print("⏳ 30초 대기..."); time.sleep(30)


# =========================================================
# 12: 증감액
# =========================================================
print("\n12: 증감액")
ws_c = with_retry(sh.add_worksheet, title="증감액", rows=1000, cols=100); time.sleep(3)

hdr_c = ['캠페인 이름','광고 이름','광고 ID','7일 평균'] + chart_dn
src = ["종합","",""]
t7r,t7s = 0,0; t7cs,t7cc = 0,0; t7vs,t7vc = 0,0
for d in chart_sd:
    for it in sorted_list:
        if d in it['data']['dates']:
            t7r+=it['data']['dates'][d]['revenue']; t7s+=it['data']['dates'][d]['spend']
            cv=it['data']['dates'][d].get('cpm',0)
            if cv>0: t7cs+=cv; t7cc+=1
            vv=it['data']['dates'][d].get('cvr',0)
            if vv>0: t7vs+=vv; t7vc+=1
t7roas = (t7r/t7s*100) if t7s>0 else 0
fds = sum(it['data']['dates'].get(chart_sd[-1],{}).get('spend',0) for it in sorted_list) if len(chart_sd)>=2 else 0
lds = sum(it['data']['dates'].get(chart_sd[0],{}).get('spend',0) for it in sorted_list) if len(chart_sd)>=2 else 0
sdc = ((lds-fds)/fds*100) if fds>0 else 0
src.append(cell_text_change(t7roas,sdc,t7s,(t7cs/t7cc) if t7cc>0 else 0,(t7vs/t7vc) if t7vc>0 else 0))

for i,d in enumerate(chart_dn):
    dr,ds_v = 0,0; dcs,dcc = 0,0; dvs,dvc = 0,0
    for it in sorted_list:
        if d in it['data']['dates']:
            dr+=it['data']['dates'][d]['revenue']; ds_v+=it['data']['dates'][d]['spend']
            cv=it['data']['dates'][d].get('cpm',0)
            if cv>0: dcs+=cv; dcc+=1
            vv=it['data']['dates'][d].get('cvr',0)
            if vv>0: dvs+=vv; dvc+=1
    d_roas = (dr/ds_v*100) if ds_v>0 else 0
    if i < len(chart_dn)-1:
        pd = chart_dn[i+1]; ps = sum(it['data']['dates'].get(pd,{}).get('spend',0) for it in sorted_list)
        chg = ((ds_v-ps)/ps*100) if ps>0 else 0
    else: chg = 0
    src.append(cell_text_change(d_roas,chg,ds_v,(dcs/dcc) if dcc>0 else 0,(dvs/dvc) if dvc>0 else 0))

rtc = []
for it in sorted_list:
    r = [it['campaign_name'],it['ad_name'],it['ad_id']]
    tr_v,ts_v = 0,0; tcpm,tcpc = 0,0; tcvr,tcvc = 0,0
    for d in chart_sd:
        if d in it['data']['dates']:
            tr_v+=it['data']['dates'][d]['revenue']; ts_v+=it['data']['dates'][d]['spend']
            cv=it['data']['dates'][d].get('cpm',0)
            if cv>0: tcpm+=cv; tcpc+=1
            vv=it['data']['dates'][d].get('cvr',0)
            if vv>0: tcvr+=vv; tcvc+=1
    ar = (tr_v/ts_v*100) if ts_v>0 else 0
    fs = it['data']['dates'].get(chart_sd[-1],{}).get('spend',0) if len(chart_sd)>=2 else 0
    ls = it['data']['dates'].get(chart_sd[0],{}).get('spend',0) if len(chart_sd)>=2 else 0
    cp = ((ls-fs)/fs*100) if fs>0 else 0
    r.append(cell_text_change(ar,cp,ts_v,(tcpm/tcpc) if tcpc>0 else 0,(tcvr/tcvc) if tcvc>0 else 0))
    for i,d in enumerate(chart_dn):
        if d in it['data']['dates']:
            dt=it['data']['dates'][d]; roas=(dt['revenue']/dt['spend']*100) if dt['spend']>0 else 0
            if i<len(chart_dn)-1:
                pd=chart_dn[i+1]; ps=it['data']['dates'].get(pd,{}).get('spend',0)
                chg=((dt['spend']-ps)/ps*100) if ps>0 else 0
            else: chg=0
            r.append(cell_text_change(roas,chg,dt['spend'],dt.get('cpm',0),dt.get('cvr',0)))
        else: r.append('')
    rtc.append(r)

with_retry(ws_c.update, values=[hdr_c]+[src]+rtc, range_name="A1", value_input_option="USER_ENTERED")
print("✅ 증감액 완료"); time.sleep(3)
apply_trend_chart_formatting(sh, ws_c, hdr_c, len(rtc), is_change_tab=True)
print("⏳ 30초 대기..."); time.sleep(30)


# =========================================================
# 13: 예산
# =========================================================
print("\n13: 예산")
bw = with_retry(sh.add_worksheet, title="예산", rows=1000, cols=100); time.sleep(3)
br = [[""] + chart_dn]
br.append(["전체 쓴돈"] + [sum(budget_by_date[d][p]['spend'] for p in product_order) for d in chart_dn])
br.append(["전체 번돈"] + [sum(budget_by_date[d][p]['revenue'] for p in product_order) for d in chart_dn])
br.append(["전체 순이익"] + [sum(budget_by_date[d][p]['revenue'] for p in product_order) - sum(budget_by_date[d][p]['spend'] for p in product_order) for d in chart_dn])
br.append(["ROAS"] + [(sum(budget_by_date[d][p]['revenue'] for p in product_order)/sum(budget_by_date[d][p]['spend'] for p in product_order)*100) if sum(budget_by_date[d][p]['spend'] for p in product_order)>0 else 0 for d in chart_dn])
br.append([""]*(len(chart_dn)+1))
br.append(["쓴돈 - 제품별"]+[""]*len(chart_dn))
for p in product_order: br.append([p]+[budget_by_date[d][p]['spend'] for d in chart_dn])
br.append([""]*(len(chart_dn)+1))
br.append(["번돈 - 제품별"]+[""]*len(chart_dn))
for p in product_order: br.append([p]+[budget_by_date[d][p]['revenue'] for d in chart_dn])
br.append([""]*(len(chart_dn)+1))
br.append(["순이익 - 제품별"]+[""]*len(chart_dn))
for p in product_order: br.append([p]+[budget_by_date[d][p]['revenue']-budget_by_date[d][p]['spend'] for d in chart_dn])

with_retry(bw.update, values=br, range_name="A1", value_input_option="RAW")
print("✅ 예산 완료"); time.sleep(3)


# =========================================================
# 14: 주간종합 준비
# =========================================================
print("\n14: 주간종합 데이터 준비")
month_groups = defaultdict(list)
for t in date_names:
    do = date_objects[t]; mk = f"{do.year}년 {do.month}월"; month_groups[mk].append(t)
month_names_list = sorted(month_groups.keys(), key=lambda x: (int(x.split('년')[0]), int(x.split('년')[1].replace('월','').strip())), reverse=True)

daily_data = defaultdict(lambda: {'spend':0,'revenue':0,'profit':0})
daily_product_data = defaultdict(lambda: defaultdict(lambda: {'spend':0,'revenue':0,'profit':0}))
for t in date_names:
    for it in sorted_list:
        if t in it['data']['dates']:
            dt=it['data']['dates'][t]; daily_data[t]['spend']+=dt['spend']; daily_data[t]['revenue']+=dt['revenue']; daily_data[t]['profit']+=dt['profit']
            p=extract_product(it['campaign_name'])
            daily_product_data[t][p]['spend']+=dt['spend']; daily_product_data[t][p]['revenue']+=dt['revenue']; daily_product_data[t][p]['profit']+=dt['profit']

wsd = {}; wps = {}
for wk in week_keys:
    wsd[wk] = {'spend':0,'revenue':0,'profit':0}; wps[wk] = defaultdict(lambda: {'spend':0,'revenue':0,'profit':0})
    for dn in week_groups[wk]:
        wsd[wk]['spend']+=daily_data[dn]['spend']; wsd[wk]['revenue']+=daily_data[dn]['revenue']; wsd[wk]['profit']+=daily_data[dn]['profit']
        for p in PRODUCT_KEYWORDS+["기타"]:
            wps[wk][p]['spend']+=daily_product_data[dn][p]['spend']; wps[wk][p]['revenue']+=daily_product_data[dn][p]['revenue']; wps[wk][p]['profit']+=daily_product_data[dn][p]['profit']

msd = {}; mps = {}
for mk in month_names_list:
    msd[mk] = {'spend':0,'revenue':0,'profit':0}; mps[mk] = defaultdict(lambda: {'spend':0,'revenue':0,'profit':0})
    for dn in month_groups[mk]:
        msd[mk]['spend']+=daily_data[dn]['spend']; msd[mk]['revenue']+=daily_data[dn]['revenue']; msd[mk]['profit']+=daily_data[dn]['profit']
        for p in PRODUCT_KEYWORDS+["기타"]:
            mps[mk][p]['spend']+=daily_product_data[dn][p]['spend']; mps[mk][p]['revenue']+=daily_product_data[dn][p]['revenue']; mps[mk][p]['profit']+=daily_product_data[dn][p]['profit']

products = ["솔로","재물","재회","29금궁합","자녀","29금","1%","별해"]
print(f"📆 월:{len(month_names_list)}, 주:{len(week_keys)}, 일:{len(date_names)}")


# =========================================================
# 15: 주간종합
# =========================================================
print("\n15: 주간종합")
ws_ws = with_retry(sh.add_worksheet, title="주간종합", rows=2000, cols=20); time.sleep(3)
sid_ws = ws_ws.id; fr_ws = []; ar_ws = []; cr_ws = 0

def ccb(pn, d, pd, sid, cr, fr, im=False):
    block = []; bs = cr
    rv = (d['revenue']/d['spend']) if d['spend']>0 else 0
    hb = COLORS["dark_blue"] if im else COLORS["dark_gray"]; cb = COLORS["navy"] if im else COLORS["black"]
    nc = len(products)+2
    block.append([pn]+[""]*(nc-1)); fr.append(create_format_request(sid,cr,cr+1,0,nc,get_cell_format(hb,COLORS["white"],bold=True))); cr+=1
    block.append(["지출 금액","구매(메타)","구매(믹스패널)","매출","이익","ROAS","CVR","전체"]+[""]*(nc-8))
    fr.append(create_format_request(sid,cr,cr+1,0,8,get_cell_format(cb,COLORS["white"],bold=True))); cr+=1
    block.append([d['spend'],0,0,d['revenue'],d['profit'],rv,0,""]+[""]*(nc-8))
    fr.append(create_number_format_request(sid,cr,cr+1,0,1,"NUMBER","#,##0"))
    fr.append(create_number_format_request(sid,cr,cr+1,3,5,"NUMBER","#,##0"))
    fr.append(create_number_format_request(sid,cr,cr+1,5,7,"PERCENT","0.00%")); cr+=1
    block.append([""]+products+["합"])
    fr.append(create_format_request(sid,cr,cr+1,1,len(products)+1,get_cell_format(cb,COLORS["white"],bold=True)))
    fr.append(create_format_request(sid,cr,cr+1,len(products)+1,len(products)+2,get_cell_format(COLORS["light_yellow"],bold=True))); cr+=1
    for lb, dk, ft, fp in [("제품별 ROAS","roas","PERCENT","0.00%"),("제품별 순이익","profit","NUMBER","#,##0"),
        ("제품별 매출","revenue","NUMBER","#,##0"),("제품별 예산","spend","NUMBER","#,##0"),("제품별 예산 비중","ratio","PERCENT","0.00%")]:
        r = [lb]; tsp = sum(pd[p]['spend'] for p in products); trv = sum(pd[p]['revenue'] for p in products)
        for p in products:
            if dk=="roas": r.append((pd[p]['revenue']/pd[p]['spend']) if pd[p]['spend']>0 else 0)
            elif dk=="ratio": r.append((pd[p]['spend']/tsp) if tsp>0 else 0)
            else: r.append(pd[p][dk])
        if dk=="roas": r.append((trv/tsp) if tsp>0 else 0)
        elif dk=="ratio": r.append(1.0)
        else: r.append(sum(pd[p][dk] for p in products))
        block.append(r)
        fr.append(create_format_request(sid,cr,cr+1,0,1,get_cell_format(bold=True)))
        fr.append(create_format_request(sid,cr,cr+1,len(products)+1,len(products)+2,get_cell_format(COLORS["light_yellow"])))
        fr.append(create_number_format_request(sid,cr,cr+1,1,len(products)+2,ft,fp)); cr+=1
    fr.append(create_border_request(sid,bs,cr,0,len(products)+2))
    block.append([""]*nc); cr+=1
    return block, cr

for mk in month_names_list:
    yr=int(mk.split('년')[0]); mn=int(mk.split('년')[1].replace('월','').strip())
    dim=sorted(month_groups[mk],key=lambda x:date_objects[x])
    fd=date_objects[dim[0]]; ld=date_objects[dim[-1]]
    mr_d=get_month_range_display(fd,ld).replace("'","")
    b,cr_ws = ccb(f"'{mk} ({mr_d})", msd[mk], mps[mk], sid_ws, cr_ws, fr_ws, im=True); ar_ws.extend(b)
    mw=[wk for wk in week_keys if any(date_objects[d].year==yr and date_objects[d].month==mn for d in week_groups[wk])]
    mw.reverse()
    for wk in mw:
        b,cr_ws = ccb(week_display_names[wk], wsd[wk], wps[wk], sid_ws, cr_ws, fr_ws); ar_ws.extend(b)

with_retry(ws_ws.update, values=ar_ws, range_name="A1", value_input_option="USER_ENTERED"); time.sleep(3)
try:
    for i in range(0,len(fr_ws),100): with_retry(sh.batch_update, body={"requests":fr_ws[i:i+100]}); time.sleep(1)
except: pass
try:
    cw=[{"updateDimensionProperties":{"range":{"sheetId":sid_ws,"dimension":"COLUMNS","startIndex":0,"endIndex":1},"properties":{"pixelSize":150},"fields":"pixelSize"}}]
    for ci in range(1,11): cw.append({"updateDimensionProperties":{"range":{"sheetId":sid_ws,"dimension":"COLUMNS","startIndex":ci,"endIndex":ci+1},"properties":{"pixelSize":100},"fields":"pixelSize"}})
    with_retry(sh.batch_update, body={"requests":cw})
except: pass
print("✅ 주간종합 완료"); time.sleep(3)


# =========================================================
# 16: 주간종합_2
# =========================================================
print("\n16: 주간종합_2")
ws2 = with_retry(sh.add_worksheet, title="주간종합_2", rows=2000, cols=20); time.sleep(3)
sid2=ws2.id; fr2=[]; ar2=[]; cr2=0; npc=len(products)+3

stl=[]
for mk in month_names_list:
    yr=int(mk.split('년')[0]); mn=int(mk.split('년')[1].replace('월','').strip())
    d=msd[mk]; roas=(d['revenue']/d['spend']) if d['spend']>0 else 0
    stl.append({'period':f"'{mk}",'type':'월별','spend':d['spend'],'revenue':d['revenue'],'profit':d['profit'],'roas':roas,'im':True,'mk':mk,'yr':yr,'mn':mn})
    mw=[wk for wk in week_keys if any(date_objects[dn].year==yr and date_objects[dn].month==mn for dn in week_groups[wk])]
    mw.reverse()
    for wk in mw:
        wd=wsd[wk]; wr=(wd['revenue']/wd['spend']) if wd['spend']>0 else 0
        stl.append({'period':week_display_names[wk],'type':'주간','spend':wd['spend'],'revenue':wd['revenue'],'profit':wd['profit'],'roas':wr,'im':False,'mk':None,'wk':wk})

ar2.append(["📊 기간별 전체 요약"]+[""]*6); fr2.append(create_format_request(sid2,cr2,cr2+1,0,7,get_cell_format(COLORS["navy"],COLORS["white"],bold=True))); cr2+=1
ar2.append(["기간","유형","지출금액","매출","이익","ROAS","CVR"]); fr2.append(create_format_request(sid2,cr2,cr2+1,0,7,get_cell_format(COLORS["dark_blue"],COLORS["white"],bold=True))); cr2+=1
t1s=cr2
for rd in stl:
    ar2.append([rd['period'],rd['type'],rd['spend'],rd['revenue'],rd['profit'],rd['roas'],0])
    bg=COLORS["light_blue"] if rd['im'] else COLORS["white"]
    fr2.append(create_format_request(sid2,cr2,cr2+1,0,7,get_cell_format(bg)))
    fr2.append(create_number_format_request(sid2,cr2,cr2+1,2,5,"NUMBER","#,##0"))
    fr2.append(create_number_format_request(sid2,cr2,cr2+1,5,7,"PERCENT","0.00%")); cr2+=1
fr2.append(create_border_request(sid2,t1s-1,cr2,0,7)); ar2+=[[""]*(npc),[""]*(npc)]; cr2+=2

for tt,tc,dk in [("📈 제품별 ROAS",COLORS["dark_green"],"roas"),("💰 제품별 순이익",COLORS["dark_green"],"profit"),
    ("💵 제품별 매출",COLORS["orange"],"revenue"),("💸 제품별 예산",COLORS["purple"],"spend"),("📊 제품별 예산 비중",COLORS["purple"],"ratio")]:
    ar2.append([tt]+[""]*(npc-1)); fr2.append(create_format_request(sid2,cr2,cr2+1,0,npc,get_cell_format(tc,COLORS["white"],bold=True))); cr2+=1
    ar2.append(["기간","유형"]+products+["합계"]); fr2.append(create_format_request(sid2,cr2,cr2+1,0,npc,get_cell_format(COLORS["dark_gray"],COLORS["white"],bold=True))); cr2+=1
    tds=cr2
    for rd in stl:
        pd_r = mps.get(rd['mk'],defaultdict(lambda:{'spend':0,'revenue':0,'profit':0})) if rd['im'] else wps.get(rd.get('wk',''),defaultdict(lambda:{'spend':0,'revenue':0,'profit':0}))
        r=[rd['period'],rd['type']]; tsp=sum(pd_r[p]['spend'] for p in products); trv=sum(pd_r[p]['revenue'] for p in products)
        for p in products:
            if dk=="roas": r.append((pd_r[p]['revenue']/pd_r[p]['spend']) if pd_r[p]['spend']>0 else 0)
            elif dk=="ratio": r.append((pd_r[p]['spend']/tsp) if tsp>0 else 0)
            else: r.append(pd_r[p][dk])
        if dk=="roas": r.append((trv/tsp) if tsp>0 else 0)
        elif dk=="ratio": r.append(1.0)
        else: r.append(sum(pd_r[p][dk] for p in products))
        ar2.append(r); bg=COLORS["light_blue"] if rd['im'] else COLORS["white"]
        fr2.append(create_format_request(sid2,cr2,cr2+1,0,npc,get_cell_format(bg)))
        ft="PERCENT" if dk in ["roas","ratio"] else "NUMBER"; fp="0.00%" if dk in ["roas","ratio"] else "#,##0"
        fr2.append(create_number_format_request(sid2,cr2,cr2+1,2,npc,ft,fp)); cr2+=1
    fr2.append(create_border_request(sid2,tds-1,cr2,0,npc)); ar2+=[[""]*(npc),[""]*(npc)]; cr2+=2

with_retry(ws2.update, values=ar2, range_name="A1", value_input_option="USER_ENTERED"); time.sleep(3)
try:
    for i in range(0,len(fr2),100): with_retry(sh.batch_update, body={"requests":fr2[i:i+100]}); time.sleep(1)
except: pass
print("✅ 주간종합_2 완료"); time.sleep(3)


# =========================================================
# 17: 주간종합_3 (일별)
# =========================================================
print("\n17: 주간종합_3 (일별)")
ws3 = with_retry(sh.add_worksheet, title="주간종합_3", rows=3000, cols=20); time.sleep(3)
sid3=ws3.id; fr3=[]; ar3=[]; cr3=0; ndc=len(products)+4

dsr=[]
for t in reversed(date_names):
    do=date_objects[t]; d=daily_data[t]; roas=(d['revenue']/d['spend']) if d['spend']>0 else 0
    wd=WEEKDAY_NAMES[do.weekday()]
    dsr.append({'period':f"'{do.month}.{do.day}({wd})",'weekday':wd,'spend':d['spend'],'revenue':d['revenue'],'profit':d['profit'],'roas':roas,'tab_name':t})

ar3.append(["📊 일별 전체 요약"]+[""]*7); fr3.append(create_format_request(sid3,cr3,cr3+1,0,8,get_cell_format(COLORS["navy"],COLORS["white"],bold=True))); cr3+=1
ar3.append(["날짜","요일","지출금액","매출","이익","ROAS","CVR",""]); fr3.append(create_format_request(sid3,cr3,cr3+1,0,8,get_cell_format(COLORS["dark_blue"],COLORS["white"],bold=True))); cr3+=1
t1s3=cr3
for rd in dsr:
    ar3.append([rd['period'],rd['weekday'],rd['spend'],rd['revenue'],rd['profit'],rd['roas'],0,""])
    bg=COLORS["light_blue"] if rd['weekday'] in ['토','일'] else COLORS["white"]
    fr3.append(create_format_request(sid3,cr3,cr3+1,0,8,get_cell_format(bg)))
    fr3.append(create_number_format_request(sid3,cr3,cr3+1,2,5,"NUMBER","#,##0"))
    fr3.append(create_number_format_request(sid3,cr3,cr3+1,5,7,"PERCENT","0.00%")); cr3+=1
fr3.append(create_border_request(sid3,t1s3-1,cr3,0,8)); ar3+=[[""]*(ndc),[""]*(ndc)]; cr3+=2

for tt,tc,dk in [("📈 일별 제품별 ROAS",COLORS["dark_green"],"roas"),("💰 일별 제품별 순이익",COLORS["dark_green"],"profit"),
    ("💵 일별 제품별 매출",COLORS["orange"],"revenue"),("💸 일별 제품별 예산",COLORS["purple"],"spend"),("📊 일별 제품별 예산 비중",COLORS["purple"],"ratio")]:
    ar3.append([tt]+[""]*(ndc-1)); fr3.append(create_format_request(sid3,cr3,cr3+1,0,ndc,get_cell_format(tc,COLORS["white"],bold=True))); cr3+=1
    ar3.append(["날짜","요일"]+products+["합계"]); fr3.append(create_format_request(sid3,cr3,cr3+1,0,ndc,get_cell_format(COLORS["dark_gray"],COLORS["white"],bold=True))); cr3+=1
    tds=cr3
    for rd in dsr:
        pd_r=daily_product_data[rd['tab_name']]; r=[rd['period'],rd['weekday']]
        tsp=sum(pd_r[p]['spend'] for p in products); trv=sum(pd_r[p]['revenue'] for p in products)
        for p in products:
            if dk=="roas": r.append((pd_r[p]['revenue']/pd_r[p]['spend']) if pd_r[p]['spend']>0 else 0)
            elif dk=="ratio": r.append((pd_r[p]['spend']/tsp) if tsp>0 else 0)
            else: r.append(pd_r[p][dk])
        if dk=="roas": r.append((trv/tsp) if tsp>0 else 0)
        elif dk=="ratio": r.append(1.0)
        else: r.append(sum(pd_r[p][dk] for p in products))
        ar3.append(r); bg=COLORS["light_blue"] if rd['weekday'] in ['토','일'] else COLORS["white"]
        fr3.append(create_format_request(sid3,cr3,cr3+1,0,ndc,get_cell_format(bg)))
        ft="PERCENT" if dk in ["roas","ratio"] else "NUMBER"; fp="0.00%" if dk in ["roas","ratio"] else "#,##0"
        fr3.append(create_number_format_request(sid3,cr3,cr3+1,2,ndc,ft,fp)); cr3+=1
    fr3.append(create_border_request(sid3,tds-1,cr3,0,ndc)); ar3+=[[""]*(ndc),[""]*(ndc)]; cr3+=2

with_retry(ws3.update, values=ar3, range_name="A1", value_input_option="USER_ENTERED"); time.sleep(3)
try:
    for i in range(0,len(fr3),100): with_retry(sh.batch_update, body={"requests":fr3[i:i+100]}); time.sleep(1)
except: pass
print("✅ 주간종합_3 완료"); time.sleep(3)


# =========================================================
# 18: 탭 순서 정리
# =========================================================
print("\n18: 탭 순서 정리")
print("  → 날짜 탭: 왼쪽=과거 → 오른쪽=최신")
print("  → 분석 탭: 날짜 탭보다 더 오른쪽 (제일 끝)")

try:
    tmp = sh.worksheet("_tmp"); sh.del_worksheet(tmp)
except: pass

try:
    all_ws = sh.worksheets()
    analysis_set = set(ANALYSIS_TAB_NAMES)
    analysis_tabs = []
    date_tabs = []
    other_tabs = []

    for ws in all_ws:
        tn = ws.title
        if tn in analysis_set:
            analysis_tabs.append(ws)
        elif parse_date_tab(tn) is not None:
            date_tabs.append(ws)
        else:
            other_tabs.append(ws)

    date_tabs.sort(key=lambda ws: parse_date_tab(ws.title))

    analysis_order = {name: i for i, name in enumerate(ANALYSIS_TAB_NAMES)}
    analysis_tabs.sort(key=lambda ws: analysis_order.get(ws.title, 999))

    final_order = other_tabs + date_tabs + analysis_tabs

    if date_tabs:
        oldest = date_tabs[0].title
        newest = date_tabs[-1].title
        print(f"  📅 날짜 탭: {len(date_tabs)}개 ({oldest} → {newest})")
    else:
        print(f"  📅 날짜 탭: 0개")
    print(f"  📊 분석 탭: {len(analysis_tabs)}개 → {[ws.title for ws in analysis_tabs]}")
    print(f"  📋 기타 탭: {len(other_tabs)}개")

    reorder_requests = []
    for idx, ws in enumerate(final_order):
        reorder_requests.append({
            "updateSheetProperties": {
                "properties": {"sheetId": ws.id, "index": idx},
                "fields": "index"
            }
        })

    if reorder_requests:
        with_retry(sh.batch_update, body={"requests": reorder_requests})
        print("  ✅ 탭 순서 정리 완료")
        time.sleep(2)
except Exception as e:
    print(f"  ⚠️ 탭 순서 정리 오류: {e}")

print("\n" + "="*60)
print("✅ 완료!")
print("="*60)
print()
print(f"📋 Meta: 최근 {REFRESH_DAYS}일만 수집 (API 호출 {REFRESH_DAYS}×3계정 = {REFRESH_DAYS*3}회)")
print(f"📋 Mixpanel: 최근 {REFRESH_DAYS}일만 수집")
print(f"📋 기존 날짜 탭: 보존됨 (삭제 없음)")
print(f"📋 새로 생성한 날짜 탭: {len(new_date_names)}개")
print(f"📋 기존 탭에서 읽은 과거 데이터: {read_count}개 탭")
print(f"📋 분석 탭: 전체 기간 기준으로 재생성")
print(f"📋 탭 순서: [기타] → [날짜: 과거→최신] → [분석탭]")
print(f"\n📊 {SPREADSHEET_URL}")
