# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmnMlchXLeL9eIuNX9RVl3O2y8unTOFy
"""

#!/usr/bin/env python3
"""
v3_ad_tw_adset.py 원본 파일의 하드코딩된 인증정보를
GitHub Secrets (os.environ) 방식으로 자동 교체하는 패치 스크립트.

사용법:
  python patch_tw_secrets.py  원본파일.py
  → 같은 폴더에 v3_ad_tw_adset_patched.py 생성
"""
import sys, os

if len(sys.argv) < 2:
    print("사용법: python patch_tw_secrets.py  원본파일.py")
    sys.exit(1)

src = sys.argv[1]
with open(src, 'r', encoding='utf-8') as f:
    code = f.read()

changes = 0

# ━━━ 1. SPREADSHEET_URL ━━━
old1 = 'SPREADSHEET_URL = "https://docs.google.com/spreadsheets/d/187gxptjGk6Bdhyp6_w14rldMSwBNve2QGDY7KzcIPTU/edit?usp=sharing"'
new1 = 'SPREADSHEET_URL = os.environ.get("SPREADSHEET_URL", "https://docs.google.com/spreadsheets/d/187gxptjGk6Bdhyp6_w14rldMSwBNve2QGDY7KzcIPTU/edit?usp=sharing")'
if old1 in code:
    code = code.replace(old1, new1); changes += 1; print("✅ 1/3 SPREADSHEET_URL 교체")
else:
    print("⚠️ 1/3 SPREADSHEET_URL 찾을 수 없음")

# ━━━ 2. META_TOKEN_DEFAULT ━━━
old2 = 'META_TOKEN_DEFAULT = "EAAPRyREHB7YBQZBatehMtIL1RiHQlOxy53L8I4ZCsbwk2bEqBUdAdOg4byBvyRQR9M3EN13J8GDoI3vDPybPyzNdoLnUJgicrObmd8AmuGzrDJIQBMXMaSQlBGbK5LexSOdO3qxox1VCu6CDPEZAE0zGMRT3AZBIxuJpwx4EjJoHKlBK5SaH0ITnM95J0AZDZD"'
new2 = 'META_TOKEN_DEFAULT = os.environ.get("META_TOKEN_1", "")'
if old2 in code:
    code = code.replace(old2, new2); changes += 1; print("✅ 2a/3 META_TOKEN_DEFAULT 교체")
else:
    print("⚠️ 2a/3 META_TOKEN_DEFAULT 찾을 수 없음")

# ━━━ 3. META_TOKENS dict (TW 계정) ━━━
old3 = '''META_TOKENS = {
    "act_1054081590008088": META_TOKEN_DEFAULT,  # Sajutight_tw (토큰1)
    "act_2677707262628563": "EAANmrZA47Te4BQy7ZA9Eq4SivQZCgxJ8zJfkr4vDAlsHQZBzpaRlv0gBuKkTTmvxgbVtdJ4vB19ZAjg4RUIfRXTEc3FGyBlZBzOTQ5IOdVrKlAmCHnOKxJQgNCZCs7pta8PRUnTZCCO6gbEU0iIkIwfoEjPkwqLQxHd8MZCTITx0s63xg4tl5sTjjZBLsIn0BgMS2jdQZDZD",  # TTsaju (토큰2)
}'''
new3 = '''META_TOKENS = {
    "act_1054081590008088": os.environ.get("META_TOKEN_1", ""),   # Sajutight_tw
    "act_2677707262628563": os.environ.get("META_TOKEN_3", ""),   # TTsaju
}'''
if old3 in code:
    code = code.replace(old3, new3); changes += 1; print("✅ 2b/3 META_TOKENS 교체")
else:
    print("⚠️ 2b/3 META_TOKENS 찾을 수 없음")

# ━━━ 4. Mixpanel 인증정보 ━━━
replacements = [
    ('MIXPANEL_PROJECT_ID = "3390233"',
     'MIXPANEL_PROJECT_ID = os.environ.get("MIXPANEL_PROJECT_ID", "3390233")'),
    ('MIXPANEL_USERNAME = "test_python_02_koo.89a064.mp-service-account"',
     'MIXPANEL_USERNAME = os.environ.get("MIXPANEL_USERNAME", "")'),
    ('MIXPANEL_SECRET = "aZeMPUkOws62FWRaxBYHPmvvgjAFfTO4"',
     'MIXPANEL_SECRET = os.environ.get("MIXPANEL_SECRET", "")'),
]
mp_ok = 0
for old, new in replacements:
    if old in code:
        code = code.replace(old, new); mp_ok += 1
if mp_ok == 3:
    changes += 1; print("✅ 3/3 Mixpanel 3개 항목 교체")
else:
    print(f"⚠️ 3/3 Mixpanel {mp_ok}/3개만 교체됨")

# ━━━ 저장 ━━━
out = os.path.join(os.path.dirname(src), 'v3_ad_tw_adset_patched.py')
with open(out, 'w', encoding='utf-8') as f:
    f.write(code)

print(f"\n{'='*50}")
print(f"총 {changes}/3 섹션 교체 완료")
print(f"저장: {out}")

# 검증: 하드코딩 토큰 잔존 체크
leaked = []
for token_fragment in ['EAAPRyREHB7YBQZBateh', 'EAANmrZA47Te4BQy', 'aZeMPUkOws62', 'test_python_02_koo']:
    if token_fragment in code:
        leaked.append(token_fragment[:20])
if leaked:
    print(f"\n⚠️ 경고: 하드코딩 토큰 잔존! {leaked}")
else:
    print("✅ 하드코딩 토큰 없음 — public repo 안전")