name: 채널별 추이차트 v6
on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install gspread gspread-formatting google-auth pandas numpy requests
      - name: Run script
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          NAVER_API_KEY: ${{ secrets.NAVER_API_KEY }}
          NAVER_SECRET_KEY: ${{ secrets.NAVER_SECRET_KEY }}
          NAVER_CUSTOMER_ID: ${{ secrets.NAVER_CUSTOMER_ID }}
          MIXPANEL_PROJECT_ID: ${{ secrets.MIXPANEL_PROJECT_ID }}
          MIXPANEL_USERNAME: ${{ secrets.MIXPANEL_USERNAME }}
          MIXPANEL_SECRET: ${{ secrets.MIXPANEL_SECRET }}
          SPREADSHEET_URL_NAVER_SA: ${{ secrets.SPREADSHEET_URL_NAVER_SA }}
        run: python 국내_채널별
